# Source of Law and Effects

## 국제법의  법원
### 법원의  유형
#### 형식적  법원

국제법의 법원으로는 19세기 법실증주의의 대두와 아울러 종전까지 조약과 국제관습법만을 말해왔다. 그러나 PCIJ가 위의 두 가지 이외에 '법의 일반원칙'도 재판기준으로 인정한 이후 '법의 일반원칙'을 국제법의 법원에 포함시키는 견해가 유력하다. 따라서 이상의 세 가지 법형식을 일컬어 형식적 법원이라고  한다.

#### 실질적  법원

법규범이란 주어진 문제에 기계적으로 적용되는 것은 아니다. 소위 해석이라는 행위를 통해서 그 내 용이 밝혀지고 특정문제에 대한 적용여부가 정해진다. 이 때 국제재판의 판결, 학설, 국제기구의 결의, 미발효조약, 국제회의와 위원회의 준비작업, 결의, 선언, 보고서 등 각종 관련요소가 고려된다. 이것들은 형식적 법원의 내용을 명확히 하기 위하여 고려되는 것으로 통상 실질적 법원이라고 한다.

#### 형식적  법원과  실질적  법원의  관계

형식적 법원의 범위와 내용을 명확히 하는 보조 자료로서 실질적 법원은 다양하지만 그중에서도 국제 판례, 학설, 국제적 결의 등이 중요하다. 조약의 해석 및 관습법의 내용은 실질적 법원의 변동에 따라서 변할  경우도  있고  (영국과  아일랜드간의  '어업관할권  사건',1974  참조),  형식적  법원과  실질적  법원이  밀접하게 관련되기 때문에 양자를 구별하는 것이 곤란할  수도  있다('리비아-말타  대륙붕  사건', 1985  참조).

###	조약
#### 입법조약과 양자조약
조약은  국제법  주체  간에  맺어지는  문서에  의한  합의이다(비엔나  조약법  조약  제2조  1a). 조약은  체약 국간에  적용되는  규범을  창설하며,  국제관습법을  보완하거나  이를  수정할  수  있다.  조약중  이른바  입법 조약(law-making treaty)은 국제사회의 일반적 규범을 정립하는 것으로서 매우 중요한 법원이다. 두 국가 간 조약의 경우에도 체약국간의 법규범 설정기능은 인정이 되며 그 법원성이 부정되지 않는다( ICJ '시실리 전자공업회사  사건',  1989  참조).

#### 조약의  제  3국에  대한  효과

조약은  제3국에  대하여  권리와  의무를  창설하지  않는다.  그러나  다국  간  조약의  규정이  관습법화할 경우  또는  관습법을  법전화한  조약의  경우에는  제3국에게도  그  법적  효과가  미칠  수  있다(ICJ  북해대륙붕 사건,1969 참조).
 
####  협력수단으로서  조약의  역할  증대
현대의 기술과 교통 및 무역의 발전은 국가들 간의 상호의존성을 더욱 증진시키고 있으며, 광범위한 분야에 있어서 공통의 관심사에 대한 규칙의 제정을 촉진시키고 있다. 따라서 조약은 국제관계상 중요한 협력의 수단이며, 이러한 협력은 관계국간의 지위를 변화시키기도 하기 때문에 조약은 흔히 변화를 위한  수단이  되기도  한다.

### 관습법

  1. 의의\
  국제관습법이란 법으로 인정된 일반관행의 증거로서의 국제관습이다(ICJ 규정 제38조 1b). ICJ에 의하면 국제관습법은 "성질상 국제사회의 모든 구성국에 대하여 똑같이 효력을 가져야 하며, 자기 사정 때문에 임의로 특정국가에 의하여 일방적으로 배제될 수는 없다"(북해대륙붕 사건, 1969). 또한 ICJ는 국제관습법의 형성요건으로서 객관적 요건으로서의 국가관행과 주관적 요건으로서의 법적 신념을 들고 있다. 
  
  2. 관습법의 증거
  
  + 국가관행의 존재: 관습법의 주된 증거는 실제의 국가관행에서 찾을 수 있다. 국가관행은 국가가 취한 행동에 관한 신문보도나 정부대변인의 성명 및 국제회의에서 행하는 성명 등의 공표된 자료와 국내 법률 및 판례에서도 찾을 수 있다.
  + 학설 및 국내외판결: ICJ규정 제 38조 1d에서 법칙결정의 보조수단으로 열거되어 있는 바와 같이 국제법학자의 저서 및 국내재판소와 국제재판소의 판결에서도 찾을 수 있다.
  + 조약: 조약도 관습법의 증거가 될 수 있는데, 조약이 관습법을 선언하고 있거나 혹은 관습법의 법전화를 의도한다면 그것은 조약의 비당사국에 대해서 관습법의 증거로 원용될 수 있다. 그러나 기존의 관습법이 조약에 의해 변화할 가능성도 있다. 

### 국가관행

  1. 의의\
  국가관행이란 당해 행위가 각국의 일반적 관행, 즉 동일한 내용의 행위가 반복하고 있음을 말한다. 그렇지만 그 관행이 반드시 완전한 획일성과 일관성을 요구하는 것은 아니다. 국가관행에는 부작위도 포함된다. 
  
  2. 기간의 문제\
  국가관행의 형성에 요구되는 시간적 요소는 일정치 않다. 중요한 것은 그 기간 내에 특별히 이해관계를 갖는 국가를 포함한 국가의 관행이 광범위하고 실제상의 일치를 보이는 것이다(ICJ 북해대륙붕 사건, 1969 참조).

### 법적 신념

주관적 요건으로서의 법적 신념이란 당해 행위의 실행 또는 억제가 법적 권리ㆍ의무의 관념을 갖는다는 규범적 인식이다. 일반적으로 이러한 요건의 인정은 국가관행의 분석을 통해 판단되는데, 당해 관행이 확고한 일관성을 가질 때에는 법적 신념의 존재에 유리한 추정이 작용된다고 볼 수 있다. 

### 법의 일반원칙

  1. 의의\
  법의 일반원칙이란 각국의 국내법에 공통된 일반적인 법원칙으로서, 국가 간의 관계에 적용할 수 있는 원칙을 말한다. 동 원칙이 ICJ의 재판준칙으로 채택된 이유는 적용법규의 부존재 내지 불명료에 의하여 재판이 불가능해지는 상태를 피하기 위한 것이었다. 
  
  2. 적용된 법일반원칙의 주요내용\
  PCIJ와 ICJ에 의해 적용된 법 일반 원칙으로는 다름과 같은 것들이 있다. 위법행위에 대한 책임발생의 원칙, 금반언의 원칙, 신의칙, 입증책임, 증거능력에 관한 제 원칙, 소의 이익, 기판력의 원칙 등이다. 
  
  3. 법원성의 인정여부
  + 부정설: 국내법원칙으로서 ICJ규정이라는 조약에 의하여 재판기준으로 되었음에 불과하기 때문에 국제법의 독자적인 법원성을 구성하는 것이 아니라고 주장한다. 
  + 긍정설: 동원칙은 ICJ뿐만 아니라 모든 국제재판에 걸친 재판준칙으로서 보편적 적용이 인정되고, 동 원칙의 적용이 조약내지 국제관습법을 매개로 하더라도 그 규범의 실체가 조약과 관습법과는 다른 연원에서 구하여지기 때문에 '법의 일반원칙'은 국제법의 독자적인 법원을 이룬다는 주장이다. 

### 판례

  1. 의의\
  ICJ 규정은 판례를 무엇이 법인가를 결정하기 위한 수단인 '법칙결정의 수단'으로 보고 있다. 그러나 ICJ 규정에서 판례의 경우 선례구속성을 인정하지 않음으로  형식적 법원은 아니다. 그럼에도 불구하고 ICJ는 참조 가능한  판례에 의거하고 있고 또한 각국도 그 판례를 중시하고 있다. 이런 의미에서 이들 판례는 실질적으로 국제 판례법이라고 불리는 실체를 형성하고 있는 것이다.
  
  2. 기능
  + 조약의 해석에 영향을 미친다. 
  + 국제관습법의 내용을 확정하는 기능을 갖는다. 
  + 새로운 법을 창조하는 기능을 갖는다. 


### 학설

  1. 의의\
  ICJ 규정은 판례와 마찬가지로 권위 있는 학설을 법칙결정의 보조수단으로 보고 있다. 그러나 실제취급에 있어서 특정학설을 직접 인용하지 않는 것이 관례이다. 그렇다고 해서 이것이 학설을 참조하지 않는다는 것은 아니다. 학설이 갖는 의의는 사건에 따라서 다르기 때문에 단일 주제에 대하여 학설이 다양하게 나타날 때 그 가치는 제한적일 수밖에 없다. 
  
  2. 적용사례
  + 외교상의 논쟁에 있어서 국가는 학자들의 견해를 자주 인용한다. 
  + 파켓트 하바나호 사건(1900)에서 미연방법원은 "다년간의 연구와 경험에 의하여 당해 주제에 정통한 법학자의 업적"에 의거해야 한다고 하였다.
  + '노테봄 사건'(제2단계, 1955)에서 재판소는 이중국적자의 보호에 관한 판례를 검토한 후에, "동일한 경향은 국제법학자의 학설과 국가실행에 있어서도 지배적이다" 라고 하였다.  

#### 국제기구의 결의와 선언
##### 법적 성질

국제기구가 채택하는 결의 및 선언은 기구의 내부적인 문제에 관한 결정을 별도로 하면 일반적으로 가맹국을 구속하는 효력을 갖지 않는다. 이는 다만 권고적인 성질의 것일 뿐이고 국제법의 형식적 법원을 구성하지 않는다. 

##### 결의의 국제법상 기능

  1. 현행 국제법의 발전을 의도하는 것과 일반적 성질의 규범내지 질서의 수립을 의도하는 것이 있다. 
  2. 국제연합헌장 및 일반국제법의 내용을 명확히 하기도 한다. 
  3. 동일한 내용의 결의가 반복 채택될 경우 이는 후에 조약화를 촉진할 뿐만 아니라 그 내용이 국제관습법화할 가능성이 있다. 
  4. 국제기구에 있어 기관의 관행은 국제법의  법원을 구성할 가능성이 있다. 

#### 형평과 자연법
##### 의의

형평은 구체적인 경우에 정의를 실현할 수 있다고 판단되는 결정요소를 말하며, 법의 해석 또는 보충을 위해 적용되는 보조규칙이다. 형평을 국제법의 법원으로 보는 사람들은 그들의 주장을 강화하고 주관주의자라는 비난을 면하기 위해서 흔히 자연법에 호소한다. 

따라서 형평, 정의, 자연법 등의 세 가지 용어는 상호 혼동되는 경향이 있다. 형평에 대한 언급에 있어서 공통의 윤리가치를 갖는다고 인정되는 국내사회와 달리, 적대적인 이념철학에 의해 유지되는 국제적 상황에 직면하게 되면 그 가치는 매우 제한적일 수밖에 없다. 

#### 적용범위

형평과 선을 적용하도록 실정법에 규정하고 있는 경우에는 이 원칙이 적용된다. 판결에서 형평과 선에 따르도록 판시하고 있는 경우에도 이에 따라야 한다. 또한 형평과 선은 일정한 경우 보충원칙으로 적용될 수 있다. 이 외에도 당사자가 형평과 선에 따라 분쟁을 재판하도록 합의하는 경우에 이 원칙이 적용되며, 이와 같은 합의를 규정하는 조항을 '형평재판조항' 이라고 한다. 


## 국제법의 효력관계
### 일반적 효력관계와 적용원칙
  
  1. 일반적 효력관계\
  조약과 국제관습법은 법적 효력에 있어서 우열관계가 없다. 따라서 조약상호간, 국제관습법 상호간, 조약과 국제관습법간에 법규가 저촉될 경우에 그 적용관계가 문제된다. 
  
  2. 적용원칙
  + 특별법 우선의 원칙\
  특정국가 간에 일반국제법의 효력이 배제된다는 의미에서 특별법 우선의 원칙이 적용됨
  + 신법 우선의 원칙\
  조약 또는 국제법 상호간에는 물론이고, 조약과 국제관습법 상호간에도 '신법은 구법을 폐기한다는 원칙이 적용된다. 
  
    1. 두 조약의 체약국이 다를 때에는 그들 국가가 함께 체약국으로 되어 있는 조약이 적용된다. 
    2. 국제연합헌장과의 관계에서 이에 저촉되는 조약상의 의무에 대하여는 항상 헌장상의 의무가 우선한다.
    3. 조약과 다른 국제관습법이 형성된 경우에 그 조약을 유지할 것인가는 체약국의 의사에 달려있다. 
    
  + 법의 일반원칙을 적용하는 경우의 효력순위 문제\
  법의 일반원칙이란 조약과 관습법의 흠결을 보충하고, 조약과 관습법의 하위에 있어 조약과 관습법이 법의 일반원칙과 저촉될 때는 조약과 관습이 우선한다. 
  + 재판상의 판결과 권위 있는 학설의 적용 시 효력순위 문제\
  ICJ규정 제38조 1항은 재판소의 판결과 학설을 "법칙결정의 수단으로 보기 때문에 이는 조약, 관습법, 법의 일반원칙 보다도 효력이 아래라고 보아야 한다. 
  + 형평을 적용할 경우 효력순위의 문제\
  형평이 국제법의 법원인지의 여부는 아직까지 확실히 말할 수 없다. 그러나 재판소가 형평과 선에 의해 재판을 할 것이 허용된 경우 재판소는 자기가 가진 형평의 관념으로 모든 국제법 규칙에 대신하는 것이 허용된다고 보아야 한다. 
  + 국제기구의 행위를 적용할 경우 효력순위의 문제\
  국제기구의 행위는 국가관행과 동일한 효력으로서 관습법의 증거가 된다. 그러나 국제기구의 구속력 있는 결정은 조약과 동일한 효력을 갖는다. 

### 상위규범으로서의 강행법규

  1. 강행법규인정의 문제\
  전통적으로 국제관계란 주권을 절대시한다는 것을 전제로 형성되었기 때문에 국가 간의 '합의 자유' 개념이 널리 인정되어 강행법규의 존재에 대한 이론의 여지가 없었다(PCIJ 로터스호 사건, 1927 참조). 그러나 1969년 '조약법에 관한 비엔나 협약'은 강행법규의 존재를 인정하고 있다. 
  
  2. 조약법 조약상 강행법규의 개념\
  일반국제법의 강행규범이란 어떠한 일탈도 허용되지 않고 또한 추후 발생한 동일한 성질은 가진 일반국제법에 의해서만 변경될 수 있는 규범으로서 국제사회 전체에 의하여 수락되고 승인된 규범을 말한다. 
  
  3. 논의된 강행법규의 주요내용에 대한 현대적 의미\
  조약의 기초단계에서는 침략행위, 집단살해, 노예매매, 등이 강행법규에 반하는 사례로 열거되었으나, 오늘날 그 내용과 범위는 국가관행과 국제 판례를 통해 확대되는 경향이 있다. ICJ는 위의 열거된 사항에 대하여 "국가가 국제사회전체에 대하여 지는 의무"이고 "모든 국가는 그 보호에 대하여 법적 이익을 갖는 것으로 간주된다"고 밝힌바 있다(바르셀로나 트랙션 사건, 제2단계 1970 참조). 따라서 강행법규란 국제사회의 기본적인 질서를 유지하기 위하여 인정되어야 할 최소한도의 불가결한 규범을 가리킨다고 볼 수 있다. 

## 국제법과 국내법의 관계
### 기존이론의 소개: 일원론 vs. 이원론

근대국가의 헌법체계는 권력분립이라는 원칙하에 법제정권은 입법부에 부여하고, 조약체결권은 행정부에 부여하고 있었기 때문에 이러한 제도적 구분에 따라  국내법과 국제법은 서로 다른 법체제를 구성한다는 이원론이 일반적 인식이었다. 그러나 국제법과 국내법의 규율영역이 점점 확대되고, 동일한 사항에 대해서도 두 가지 법의 규율이 중복적용 내지 저촉되는 경우가 증가함에 따라 양자를 일원적으로 파악하려는 경향이 나타났으며 이를 일원론이라고 한다.

### 이원론 

  1. 주요내용\
  국제법과 국내법은 그 규율영역을 달리할 뿐만 아니라, 그 타당성의 근거에 있어서도 국제법은 복수국가의 의사합치에 의하고 국내법은 국가의 단독의사에 의한다고 본다. 따라서 양자는 각각 독립한 법체계를 구성하므로 상호저촉관계가 발생하는 일은 없으며, 국제법이 국내적으로 효력을 갖기 위해서는 국제법이 국내법으로 바뀌어야 한다는 변형이론을 내놓고 있다.  대표적 학자로는 트리펠과 안치로티, 오펜하임 등이 있다. 

  2. 문제점
  + 이원적 법체계와 국가책임문제\
  국가가 국제사회에 대하여 국가책임을 진다는 것은 국제사회의 통일적 법질서를 의미하는 것이 된다. 그러나 이들 두 법체계가 완전히 별개의 법체계라면 양자가 서로 저촉한다고 해도 국가가 대외적으로 책임을 질 필요가 없으나 현실적으로 그것은 용납이 되지 않는다는 문제가 생기게 된다. 
  
  + 변형이론의 적용문제\
  국제법규 중에는 국내법으로 변형되지 않고 그대로 국내에 적용되는 경우(국제 관습법)가 적지 않으므로 모든 경우에 이것이 타당한 것은 아니다. 

### 일원론

이른바 일원론의 주장은 국제법이 실제로 국내적으로 적용되고 있다는 법인식을 그 기반으로 하고 있다, 이러한 일원론은 다시 국제법과 국내법 양자의 효력관계를 둘러싸고 국내법우위 일원론과 국제법우위 일원론으로 대립한 바있다. 그러나 국내법우위 일원론은 국제법의 타당근거와 범위가 국내법에 의해서 결정되며 나아가 결국 국제법의 존재를 부인하게 됨으로 해서 오늘날 국내법우위 일원론은 거의 받아들여지지 않고 있어 최근에는 국제법 우위 일원론이 유력하다. 여기에 있어서도 그 근거는 주장하는 사람에 따라서 다르다.

### 기존이론의 문제점

국제법과 국내법에 관한 이원론 내지 일원론이 반드시 현실에 있어 국내법과 국제법의 관계를 정확히 설명하여 주는 것은 아니다. 이 두 개의 법체계사이에는 일방이 타방에 저촉할 경우라도 어느 것이 당연히 무효로 되는 일은 없으며, 또한 양법은 완전히 별개로 존재하지도 않는다. 따라서 양자의 관계를 바로 보기 위해서는 국제의무의 이행에 관한 국제 판례와 조약의 수용에 관한 각국의 헌법규정 등에 따라 실증적으로 검토하여야만 한다. 

## 국제법에 있어서 국내법의 지위
### 국내적 행위의 국제적 효력

국가의 국내법상 행위가 국제법의 기준에 합치하지 않을 경우에 그 국가 행위의 국제적 효력은 어떻게 되는가의 문제에 대해 국제 판례는 일관되게 그 효력을 부정하고 있다 (관련사례: 노르웨이어업사건(1951),어업관할권사건(1974) 및 노테봄사건 (1955) 참조)

### 국내법 원용과 국제적 의무

국가는 자국의 국내법을 원용하여 국제법상의 의무를 피할 수 없다. 이는 PCIJ와 ICJ에서 수차례에 걸쳐 언급해온 원칙이다. 이에 관한 사례로서는 '단찌히 거주 폴란드국민의 취급에 관한 권고적 의견(PCIJ, 1932)'과 최근의 사례로서 '국제연합본부협정사건(ICJ, 1988)'을 들 수 있다. 

그러나 조약체약국간의 관계에서 국내법규정이 조약규정에 우선할 수 없음이 일반적으로 승인된 국제법원칙이라고 하더라도 이러한 원칙이 조약에 반하는 국내법을 당연 무효로 하는 것은 아니며, 다만 국가가 국제적 의무와 양립하는 형태로 행동하도록 의무화한 것이다. 

### 재판준거상 전제적 사실로서 국내법의 의의 

국제재판상 당해 문제에 대하여 국제법상의 특별한 규칙과 기준이 존재하지 않을 때, 국제재판에서 관련국내법의 규정과 제도를 당해 문제해결의 전제적 사실로서 인정하여야 할 때가 있다('바르셀로나 트랙션사건', ICJ, 1970 참조). 이는 만일 재판소가 국내법의 관련제도를 무시하여 결정할 경우에 중대한 법적곤란을 초래하게 될 가능성이 클 뿐만 아니라, 재판소가 현실과의 접촉을 상실하게 되기 때문이다. 

## 국제법의 국내적 효력
### 국제관습법의 국내적 효력

국제관습법은 일반적으로 특별한 국내적 조치를 거치지 않고 국내적 효력이 부여되는 것이 통례이다( '파케트 하바나'호 사건, 1900 과  추적권에 관한 캐나다의 '노스'호 사건, 1906 참조).

국제관습법의 효력에 관하여 많은 국가에서 법률과 동등하거나 우월한 효력을 부여하고 있는 것으로 해석된다. 그러나 영국의 경우 판례법상 제정법의 우위적 적용이 인정되고 있다. 

### 조약의 국내적 효력
#### 조약의 국내적 수용방식 

일반적으로 조약에 국내적 효력을 부여하는 방법에는 두 가지가 있다. 하나는 조약의 내용을 국내법으로 변형하는 것이고, 다른 하나는 조약을 있는 그대로 국내법으로 수용하는 방식이다. 후자가 오늘날 많은 국가들이 취하고 있는 방식이다. 그러나 일반적 수용의 경우라 하더라도 조약규정의 성질에 따라 조약 내지 특정규정을 그대로 국내재판소에서 수용할 수 없는 경우가 있다. 이런 때는 국내적으로 집행을 구체화 할 수 있는 국내입법을 통하여 실시하게 된다. 

#### 국내적으로 수용된 조약의 효력순위

국내적으로 수용된 조약의 효력순위는 각국의 헌법에 따라 다르다. 일반적인 경향으로는 법률과 동등하거나, 이에 우위 하는 효력이 부여되고 있다. 이하 주요 국가의 경우를 살펴보면 다음과 같다. 

  + 미국의 경우\
  조약이 연방 법률과 동등한 효력을 갖는 것으로 판례상 확립되어 있다. 이 경우에 신법우선의 원칙에 의하여 조약에 저촉되는 법률제정에 의하여 구 조약의 적용이 배제될 가능성이 발생할 수 있으나, 국가는 자국의 국내법을 원용하여 국제적 의무를 면할 수는 없으므로 가능한 양자가 합치되도륵 해석할 것이 요구된다. 

  + 프랑스의 경우\
  법률에 대한 조약의 우위를 헌법상 명기하고 있다.
 
  + 일본의 경우\
  일본 헌법의 경우도 조약 및 확립된 국제법규의 성실한 준수를 규정하고 있는데 이는 법률에 대한 조약의 우위를 인정한 것으로 해석되고 있다. 

  + 네덜란드 및 오스트리아의 경우\
  네덜란드 헌법 및 오스트리아 헙법은 헌법에 대한 조약의 우위를 인정하고 있기 때문에 조약의 승인에는 헌법 개정과 동일한 승인절차를 밟을 것이 요구된다. 

  + 우리나라의 경우\
  학설상의 다툼은 있지만 조약의 국회승인 절차와 헌법개정절차의 차이점을 비교해 볼 때 조약에 대한 헌법 우위설을 취하는 입장이 유력하다. 