# Subject of International Laws: States

## 국가

국제법은 국가의 권리ㆍ의무에 관하여 많이 연관되어 있는 법체제이므로 국제법의 관점에서 과연 국가가 무엇을 의미하는가에 관해서 확실히 이해할 필요가 있다. 그러나 국가의 의미를 법률적으로 확정한다는 것이 생각처럼 쉬운 일은 아니다. 이하 국제법상 일반적으로 논해지고 있는 바를 살펴보기로 한다. 

### 국가의 요건과 계속성
#### 일반적 요건
국제인격을 갖는 국가의 요건 내지 기준으로서 흔히 인용되는 것은 '국가의 권리ㆍ의무에 관한 몬테비데오협약(Convention on Rights and Duties of States,1933) 제1조에서 정하고 있는  항상적 주민, 일정한 영토, 정부, 독립 내지 타국과 관계를 맺을 수 있는 능력 등 이다. 그러나 이러한 요건을 충족하더라도 자결권의 실질적인 결여나 위법한 무력행사의 결과 국가가 수립된 경우 국가성을 인정받지 못한 경우가 있다. 대표적인 예로서는 1965년 스미스 정권의 남로디지아와 제2차 대전 중 일본에 의해 성립된 만주국이 있다. 

#### 국가의 계속성과 동일성
##### 계속성과 동일성과의 관계
  국가는 그 정부나 영토 또는 인구에 변화가 발생하더라도 일반적으로 요구되는 국가의 요건을 충족하고 있는 한, 동일국가로서 계속 존속한다. 여기서 말하는 국가의 계속성과 동일성은 별개의 개념으로서 국가의 계속성은 필연적으로 국가의 동일성을 포함하고 있지만, 국가가 동일성을 갖고 있다고 해서 반드시 국가가 계속성을 유지한 것은 아니다. 
  
##### 국가구성요건이 변경된 경우

  1. 영토나 인구변동의 경우
  + 국가의 구성요건 중 영토의 변경이나 인구의 증감이 그 자체로서 국가의 계속성에 영향을 주지는 않는다. 
  + 그러나 영토를 완전히 상실한 경우 일반적으로 그 국가는 소멸한 것으로 본다. 
  
  2. 정부변경의 경우
  + 정부의 변경과 관련하여서는 국내제도의 개정절차에 따른 변경, 국가의 명칭변경 또는 어느 국가의 혁명정부에 대한 불승인 등 이 모든 것이 국가의 계속성에 영향을 주지 않는다.
  + 더 나아가 국내제도와 통치형태를 변경하는 혁명의 경우에도 국가의 계속성 및 동일성에는 변함이 없다.
  
  3. 군사적 점령의 경우
  + 1930년대 이후의 국가실행에 의하면 위법한 무력행사의 결과로서 이루어진 국가영역의 병합은 그 자체로서 국가성을 소멸시키지 않는다고 본다. 
  + 따라서 위법하기는 하지만 실효적으로 병합된 국가의 경우 국가의 계속성은 문제가 있다 하더라도 외국지배가 배제되고 재조직된 후에는 그 국가로서의 동일성이 유지된다고 본다.

#### 국가의 소멸
국가의 계속성 및 동일성에 관한 규칙이 국가소멸의 유무에 있어서도 그대로 적용이 된다. 따라서 항상적 주민이 완전히 없어진다면 그 국가는 소멸하였다고 간주된다. 그러나 기존 국가가 국가구성요건의 하나를 충족시키는 데 부족함이 있다고 하더라도 일반적으로는 국가의 계속성에 유리한 추정이 적용되고 있는 것이 현실이다(예: 무정부상태가 장기간 계속됨으로 해서 실질적으로 독립을 상실한 경우). 

### 국가승인
#### 의의
국제사회에 새로운 국가가 성립한 경우에, 그 국가의 국제법적 주체성을 기존의 국가가 승인하는 것을 말한다. 이러한 개념은 국가가 성립한 경우에 그 성립을 인정하는 기관이 국제사회에는 존재하지 않기 때문에 기존의 국가가 일정한 정치적 판단에 기인한 일방적ㆍ재량적 행위로서 새로운 국가를 개별적으로 인정하게 하는 것으로 국제사회가 아직까지 덜 조직화 되어있음을 나타내는 것이다. 국가승인의 법적 성질에 대하여는 기존의 국가에 의해 승인됨으로써 비로소 국제법상 국가로서의 법인격을 갖는다는 소위 '창설적 효과설'과 신국가는 이미 국가로서의 자격요건을 갖추어 성립했기 때문에 국가로서의 법인격은 이미 가지며, 승인은 다만 이러한 신국가의 지위를 확인하고 선언함에 불과하다는 소위 '선언적 효과설'의 둘로 나뉘고 있으나 오늘날 선언적 효과설이 통설로 되어있다. 

#### 국가승인의 요건
##### 요건
국가승인의 요건에는 객관적 요건으로서 국가성의 기준으로 되어있는 일정한 영토, 일정한 주민, 실효적 정부, 외교능력 등이 전제로 되며, 국내에서 실효적이고 자주적인 통치를 확립하고 있을 것이 요구된다. 또한 주관적 요건으로서는 승인되는 국가가 국제법을 준수할 의사와 능력을 갖는 것이 필요하다. 그러나 오늘날 국제법의 타당성을 적극적으로 부정하지 않는 한 주관적 요건의 의미는 거의 없다. 

##### 상조의 승인(premature recognition)
국가승인의 요건을 충족하지 않은 상태에서 행하는 승인을 상조의 승인이라 하며 이는 이론상으로는 위법한 행위가 되나 국가 승인의 판단은 승인하는 국가의 재량행위이므로 승인국과 피승인국간에는 합법적인 승인으로 취급될 수 있다. 그러나 명백히 요건을 갖추지 못한 국가의 승인은 반란군에 대한 원조행위로 간주되어 본국에 대한 불법적 간섭행위를 구성할 수도 있다. 
  
#### 불승인주의
국가승인제도와 관련한 역사적 사실로서 국제법에 위반한 방법에 의한 국가의 성립에 대하여는 국가승인을 부여해서는 안 된다는 주장을 말한다. 이는 오늘날에 있어서도 여전히 국제연합헌장에 위반한 방법으로 수립된 국가나 기타의 사태에 대하여 일반적으로 불승인주의의 적용이 가능하기도 하다(예: 1932년 만주국성립의 경우 미국 및 국제연맹의 태도/1965년 국제연합 안전보장이사회에 의한 남로디지아 불승인요청件). 그러나 이러한 불승인주의가 국제법상 확립되어 있는 원칙이라고 볼 수 있는지에 대해서는 의문이 있다. 
  
#### 국가승인의 방식
##### 명시적 승인과 묵시적 승인
명시적 승인이란 선언, 통고, 조약상의 명문규정, 국제회의에서의 결의문 채택 등의 방법에 의하여 승인의 의사를 명백히 표시하는 것을 말한다. 국가승인이란 명시적으로 하는 것이 통상적인 방식이다. 이에 대하여 독립의 경위가 복잡한 경우에 본국과의 관계를 고려하여 묵시적 승인이 행해지는 경우가 있다. 

여기서 말하는 묵시적 승인이란 일정한 행위에 의하여 간접적으로 승인의 의사가 추정되는 경우를 말한다. 그러나 미승인국이 다자조약의 당사국이 되더라도 이에는 승인의 효과가 발생하지 않는다는 것이 국제법의 확립된 원칙이다. 

##### 법률상 승인과 사실상 승인
법률상 승인이란 법률상의 국가에 대한 승인을 말하는 것이고, 사실상 승인이란 신국가의 권력에 문제가 있거나 국제법을 준수할 의사나 능력에 대하여 의문이 있음에도 불구하고 신국가와 공식적인 관계를 설정할 필요가 있는 경우에 행하여지는 승인 방식을 말한다.

사실상의 승인은 법률상의 승인으로 이행되는 것이 예정되기 때문에 그런 의미에서 잠정적이기도 하다. 그러나 사실상 승인의 요건이 충족되지 않을 경우 승인을 철회할 수도 있다. 

#### 승인의 효과
국가승인에 의하여 신국가는 승인국과의 사이에서 일반국제법상의 권리의무를 완전히 취득한 주체로 간주되며, 주권국간의 관계를 규율하는 일반국제법의 규칙이 신국가와 승인국 사이에 적용된다. 승인의 효과는 상대적이며 승인국과 피승인국간에서만 발생하고, 제3국과 피승인국과의 관계에는 미치지 않는다.
  
#### 미승인국의 지위
타국은 승인을 부여하지 않더라도 실효적 지배를 확립한 정치적 존재로서 갖는 미승인국의 권리ㆍ의무 그 자체를 부인할 수 없기 때문에 미승인국이라 하더라도 승인의 법적 효과를 한정적ㆍ단편적으로 향수 할 수 있다. 이 경우 필요하다면 미승인국의 권리ㆍ의무의 실현은 제3국의 기관을 통해서 행해질 수 있다. 

### 정부승인
#### 의의
일반적으로 말할 때 합법적으로 성립한 정부를 법률상의 정부라고 부르는 것에 반해 비합법적으로 성립한 정부를 사실상의 정부라고 부른다. 정부승인이란 사실상의 정부가 지방적으로 권력을 확립한 때가 아니라 당해 국가의 일반적ㆍ사실상의 정부가 되었을 때 그 정부가 국가를 실효적으로 지배하고 그 국가를 대표하는 능력이 있는가의 여부를 확인할 필요가 있기 때문이다. 그러나 정부승인을 받지 않았다고 하더라도 국내에서 실효적 지배를 확립하고 정부는 그 국가의 유효한 정부이다. 정부승인의 성질에 대하여는 국가승인의 경우와 마찬가지로 선언적ㆍ확인적으로 보는 것이 일반적이다. 

#### 정부승인의 요건
정부승인의 요건으로서 첫째, 신정부가 영역일반 및 주민에 대하여 실효적 지배를 확립하는 것이 필요하며 둘째, 국가를 대표하는 의사와 능력을 갖는 것이 필요한 데 특히 구정부의 조약상의 의무를 이행하는 것이 필요하다. 이와 같은 요건을 갖추지 못했음에도 불과하고 정부승인을 하는 것을 상조의 승인이라고 한다(예: 스페인 내전 초기 1936년 독일과 이태리가 프랑코 정권에 대해 상조의 승인을 한 바 있다).  

정부승인제도와 관련하여 소위 정통주의라는 것이 역사적으로 존재한 적이 있었다.  나폴레옹 전쟁이후 구라파에서 생겨난 군주주의적 정통주의를 비롯하여 20세기 들어 중ㆍ남미를 중심으로 입헌주의적 정통주의 (소위 말하는 '토바르주의') 등이 주장되었다. 그러나 이러한 주장은 정부승인제도와 관련하여 각국의 정책적 입장의 표명일 뿐 국제법상 정부승인의 요건으로 확립된 법원칙은 아닌 것이다. 

#### 정부승인의 효과 및 승인 불요론
##### 정부승인의 효과
신정부는 승인국에 대하여 일반국제법상의 권리ㆍ의무를 주장할 수 있다. 또한 구정부가 외국정부와 체결한 조약상의 권리ㆍ의무가 원칙적으로 회복ㆍ승계된다. 그리고 정부승인의 효과는 원칙적으로 신정부가 사실상 성립한 때까지 소급해서 적용된다. 승인의 소급효는 국가의 계속성을 유지한다는 측면에서 볼 때 매우 중요하다. 외교관계의 단절이 정부승인을 무효로 만드는 것은 아니나, 이미 승인하고 있는 정부 이외의 정부를 그 국가의 정부로 인정할 경우에 이미 승인하였던 정부승인을 취소할 수 있다(1992년 우리나라와 대만정부와의 관계 참조).

##### 정부승인 불요론
정부승인 문제는 국내문제불간섭의 원칙과 충돌하기 쉽고, 비합법적으로 성립한 정부에 대해 승인 여부를 결정한다는 것이 여러 가지로 곤란한 문제를 야기하기 때문에 최근에는 국가실행상 정부승인을 폐지 내지 회피하는 경향이 있다. 이러한 태도는 오늘날 많은 나라들에 의해서 받아들여지고 있는데 이는 정부승인과 승인되는 정부에 대한 평가는 구별되어야 한다는 실제적 요청과 더불어 신정부와의 관계를 보다 탄력적으로 처리해야할 필요성에서 발생한 것이라고 할 수 있다. 

### 교전단체의 승인
교전단체의 승인이란 일국 내에 내전이 진행되고 있는 과정에서 반란단체가 일정한 지역에 실효적 정부를 수립하여 그 지역에 중앙정부의 지배가 미치지 않게 된 경우, 외국 또는 중앙정부가 그 반란단체를 승인하고 일정한 국제법상의 자격을 부여하는 것을 말한다. 중앙정부가 승인을 한 경우 반란단체는 그 지역의 외국이익을 보호할 책임을 지게 되며 내전에는 전쟁법규가 적용되게 된다. 외국정부가 승인한 경우 반란단체는 당해 지역에 있어서 승인한 외국정부의 이익보호에 관한 책임을 지게 된다. 

그리고 그 외국은 내전이 계속 중인 중앙정부와 반란단체에 대하여 중립의무를 지게 된다. 그러나 오늘날 내전에는 외국정부가 개입하는 일이 많아지고, 중앙정부도 반란단체에게 법적 자격을 부여하는 것을 꺼리기 때문에 교전단체 승인제도의 의미는 줄어들고 있다. 

### 국가승계
#### 국가승계의 개념
국가승계란 일정한 지역을 통치하는 국가가 변경되어 그 영역에 대한 주권이 변경된 경우에 그 때까지 그 영역의 국제관계에 관하여 책임을 지고 있던 구통치국(선행국)의 권리ㆍ의무가 신통치국(승계국)에 어떻게 이전되어야 하는가 하는 문제이다. 이 문제에 관해서는 국제연합에서 국제법 법전화사업의 일환으로 1978년과 1983년 각 각 두 개의 조약으로 채택된 바 있다. 

#### 조약의 승계(1978년 '조약에 대한 국가승계에 관한 비엔나 협약') 
##### 비엔나협약의 기본입장
조약관계의 법적 안정성을 고려하여 일반적으로 계속성의 원칙(rule of continuity)을 적용하지만, 예외적으로 신생독립국의 경우에 민족자결주의 원칙에 대한 고려에서 모든 조약관계를 새로이 시작한다는 백지출발주의 원칙(clean slate rule)을 적용한다.   국가영역의 일부가 타국의 영역에 편입된 경우에 선행국의 모든 조약은 원칙적으로 그 영역부분에 대해서는 효력을 잃고 승계국의 조약이 적용된다. 이 경우에는 조약의 효력범위가 영역적으로 이동하므로 '조약국경이동의 원칙'(moving treaty frontiers' rule) 이라고 부른다. 

##### 백지출발주의의 예외
조약의 내용이 국제관습법으로 되어 있는 경우와 조약에 의하여 확정된 국경의 제도에 관한 권리ㆍ의무 및 그 밖의 일정한 영역적 제도 등에 대하여는 국가승계가 어떠한 영향도 미치지 못한다. 그러나 군사기지에 관한 내용은 백지출발주의가 적용된다. 

#### 국가재산, 공문서 및 국가채무의 승계
1983년 국가재산 등에 관한 비엔나협약에 의하면 국가의 재산ㆍ공문서ㆍ채무 등에 관하여 국가결합의 경우는 포괄 승계되고, 분리ㆍ분열의 경우는 분할 승계된다. 영역의 일부이전의 경우에는 합의에 의한 승계가 행해지고 신생독립국의 경우에는 특별한 합의에 의하는 것으로 하고 있다. 여기서 말하는 국가재산이란 국가승계시 선행국의 국내법에 따라 선행국이 소유하고 있던 재산ㆍ권리 및 이익을 말하며, 공문서란 그 일자 및 성질의 여하를 불문하고 선행국이 그 기능의 행사에 있어서 작성하거나 수령한 문서로서 그 목적의 여하를 불문하고 국가승계일에 그 국내법에 따라 소유하고 있던 문서로서 직접 또는 그 관리 하에 소유한 것을 말한다. 국가채무란 타국ㆍ국제기구 또는 다른 국제법 주체에 대한 선행국의 재정상의 의무로서 국제법에 따라 발생한 것을 말한다. 

#### 사권 및 국가계약의 승계
선행국의 국내 법령 하에서 유효하게 취득한 재산권 및 기타의 사권은 통치국이 변경하더라도 존속하며, 특히 주권의 변경시 기득권에 대하여 승계국은 이를 존중하지 않으면 안 된다. 특히 국가와 특허권소유자인 기업 또는 사인 간에 체결된 국가계약의 경우 기득권 존중원칙에 의하여 승계된다는 것이 종래의 입장이었다.  그러나 오늘날 천연의 부와 자원에 대한 영구적 주권과 관련하여 이를 부정하는 입장도 있다.  

## 국제기구
### 국제기구와 국가주권과의 관계

오늘날 국제사회에는 국경을 넘는 경제사회활동의 발전에 따라 한 국가만으로는 대처가 불가능한 사항이 발생하여 국가이외의 단체가 다양한 활동을 하고 있다. 이 중 국제기구는 국가와는 별개의 단위로 활동하고 특정목적을 수행할 필요에서 일정한 국제법상의 주체성을 인정받는 것이 보통이다. 그렇다고 해서 국제기구가 국가와 동일한 지위를 누린다는 것은 아니다. 오히려 모든 국제기구는 그 존속 및 활동의 모든 단계에서 국가에 크게 의존하고 있다.  따라서 국제기구는 기구자체의 자립성유지라는 측면과 국가주권에 대항하여 기구의 실효성을 높여야 한다는 문제점을 갖고 있다. 반면에 국제기구는 자체의 결의를 통하여 가맹국의 권리ㆍ의무와 관련된 사항에 영향을 미쳐 전통적인 국가주권개념에 변화를 주고 있다. 이러한 과정에서 끊임없이 일어나는 국가주권과의 충돌관계를 해결해 주어야 하는 것이 또한 문제이다. 

### 정의 및 분류
#### 정의
오늘날 국가의 정의에 대응하는 일반적으로 승인된 국제기구의 정의는 확립되어 있지 않다. 그러나 일반적으로 국제기구의 요건으로 ICJ의 판결('국제연합 근무 중 입은 손해배상에 관한 사건, 1949 참조)을 들고 있다. 

이에 의하면 국제기구란 다음의 4가지 요소로 정의될 수 있다. 첫째 국제법상의 합의(조약)에 의해 설립되고, 둘째 국가가 주요 구성원인 독립한 단체로서, 셋째 고유한 의사를 가지고, 넷째 구성원의 공통이익을 실현하는 것을 그 목적으로 하는 것이어야 한다. 일반적으로 국제기구로서 다루어지는 것은 '정부 간 국제기구' 만을 의미하며 재판기능을 주목적으로 하는 사법기관은 제외하는 것이 통례이다. 

#### 국제기구의 분류
국제기구는 다양한 기준에 의하여 다음과 같이 분류될 수 있다. 

  1. 가맹국의 범위에 의해 **보편적 국제기구**와 **지역적 국제기구**로 나눌 수 있다. 
  
  2. 국제기구의 목적과 임무를 기준으로 하여 **정치적 국제기구**와 **비정치적 국제기구**로 나눌 수 있다. 
  
  3. 국제기구가 갖는 권능의 성질에 따라 **일반적 국제기구**와 **초국가적 국제기구( 유럽공동체)**로 나눌 수 있다. 
  
  4. 오늘날에는 상업적 성격을 갖는 **국제기구(국제전기통신위성기구, 국제심해저기구 등)**도 나타났다. 
  
  5. 우리가 말하는 국제기구와 구별하여야 할 것은 **'비정부간 단체'(NGO: Non-Governmental Organization)**이다. 이들은 국가 간의 단체가 아니라 민간차원의 합의에 의하여 설립되어 국제적인 활동을 하는 단체들을 말한다. 

### 국제기구 일반론
#### 국제기구에 적용되는 법규
국제기구에 관련되는 국제법 및 각국의 국내법 그리고 관련되는 국제 판례와 국내 판례를 총괄하여 강의의 편의상 국제기구법이라고 부른다. 따라서 국제기구법이라는 명칭의 국제성문법이 존재하는 것은 아니다. 국제기구법의 법원으로서는 개별 국제기구의 설립조약과 국제기구의 특권 및 면제에 관한 조약을 비롯해 국제기구가 그 본부를 둔 국가와 체결하는 본부협정 등이 있다. 이외에도 법원으로서 문제가 되는 것은 국제기구에 관한 국제관습법이 얼마나 성숙이 되어 있는가 하는 점이다. 따라서 오늘날에는 국제기구의 구체적 의무와 권능을 개별 기구마다 어떻게 인정할 것인가 하는 점에 대해서 가맹국 또는 관련국가의 재량에 맡길 수는 없다는 점에 대해서 의견을 일치를 보이고 있기 때문에 국제기구의 실체와 절차를 규정한 관련조약을 엄밀하게 해석하는 것이 주요 과제로 되어있다. 

#### 국제기구의 설립과 해산
##### 국제기구의 설립
국제기구의 설립의 형식을 일정하지 않으나, 정부 간에 체결되는 설립조약에 의하여 설립되는 것이 일반적이다. 이외에도 기존 국제기구의 결의에 따라 설립되는 경우가 있다(예: 국제연합공업개발기구). 이러한 절차로 설립되는 경우라 하더라도 설립조약에 근거한 국제기구와 그 지위와 권능에 있어서 차이가 있는 것은 아니다. 

##### 국제기구의 해산 및 승계

  + 국제기구의 해산은 그러한 취지의 규정이 설립조약에 있으면 그 규정에 따라 행해진다. 존속기간이 정해져 있는 경우에는 기간 만료 전에 당사국에 의해 기구계속에 대한 합의가 없는 겨우 존속기간의 만료로써 자동적으로 해산된다. 해산규정도 존속기간의 규정도 없는 경우에 기구의 해산은 가맹국의 만장일치로써 행해진다. 
  
  + 국제기구의 해산 내지 소멸의 경우 그 기구의 임무와 자산이 새로운 기구에 의하여 승계되는 문제가 발생할 수 있다.  국제기구의 승계문제는 국가승계와 달리 일반원칙이 정해져 있지 않다. 따라서 국제기구 승계의 경우 어떠한 임무와 자산을 승계할 것인가 하는 것은 개별적으로 정해질 수밖에 없다. 

#### 국제기구의 구성원
국제기구 구성원 자격은 설립조약에 규정되며 그 구성원은 원칙적으로 국가이다. 그러나 국가 이외의 단체도 때로는 정규구성원의 자격을 갖지 않은 채 국제기구에의 참가가 인정될 경우가 있다(예: 팔레스타인 해방 기구는 참관인 자격으로 국제연합에 대표자를 파견했다). 또한 오늘날에는 국가 이외의 단체도 국제기구의 구성원으로서 (예: 국제노동기구의 구성원은 정부, 노동자 및 사용자 대표로 구성되어 있다)국제기구에 참가할 수 있다. 

#### 국제기구의 주요 내부기관 
##### 국제기구일반
국제기구는 내부기관으로서 대체로 총회와 이사회 그리고 사무국 등이 3부로 구성을 취하는 것이 일반적이지만 이것이 국제기구의 요건은 아니다. 예컨대 과거 국제연맹은 총회, 이사회, 사무국의 3부로 구성을 하였지만 국제연합은 주요기관으로서 총회, 안정보장이사회, 경제사회이사회, 신탁통치이사회, 국제사법재판소, 사무국의 여섯 기관으로 구성되어있다. 

##### 국제연합의 주요 내부기관

  + 총회
  
    + 구성: 모든 국제연합 가맹국으로 구성되고, 각 가맹국은 5인 이하의 대표자를 출석시킬 수 있다. 
    + 권한: 헌장의 범위 내에 있는 문제나 사항 또는 헌장에 규정된 기관의 권한과 임무에 관한 문제나 사항을 검토할 뿐만 아니라, 안전보장이사회에 의해서 규제되는 경우를 제외하고는 이들 모든 문제나 사항에 대하여 가맹국이나 안전보장이사회에 권고를 할 수 있다. 
    + 회기: 총회는 매년 1회씩 9월 셋째 화요일에 개최하며, 안전보장이사회 의 요청 또는 가맹국 과반수의 요청이 있을 경우 사무총장은 임시총회를 소집하여야 한다. 이외에도 안전보장이사회가 총회 폐회중 그 임무수행에 실패했을 경우 안전보장이사회의 9개 이상 이사국의 요청 또는 가맹국 과반수 이상의 요청에 의거 개최되는 긴급특별총회가 있다. 
    + 의결: 각 가맹국 대표는 하나의 투표권을 가지며, 표결은 출석하여 투표하는 구성국의 과반수에 의하나 중요한 문제는 출석하여 투표하는 가맹국의 2/3로 행해진다. 그러나 헌장 개정안의 채택이나 헌장 재검토절차에는 전 가맹국 2/3의 찬성을 요한다. 

  + 안전보장이사회
  
    + 구성: 5개의 상임이사국(미국, 영국, 프랑스, 러시아, 중국)과 10개의 비상임이사국으로 구성되며, 비상임이사국은 국제연합에의 공헌도 및 형평한 지리적 배분을 고려하여(아프리카 3, 아시아 2, 라틴아메리카 2, 서구 기타 2, 동구 1) 임기 2년으로 매년 5개국씩 총회에서 선출한다. 비상임이사국의 연속 재선은 금지된다. 
    + 의결: 각 이사국은 하나의 투표권을 가지며, 의결은 절차사항(9개 이상 이사국의 찬성투표 요구)과 실질사항(상임이사국을 포함한 9개 이상 이사국의 찬성 필요)에 따라 다르다. 실질사항의 경우 상임이사국에게는 거부권이 인정되고 있으며, 토의 주제가 절차사항인가 실질사항인가에 대한 선결문제도 실질사항으로 되어 있기 때문에 이중거부권의 문제가 생긴다. 절차사항에 대해서는 구체적으로 헌장 28～32조에 열거되어 있다. 

  + 경제사회이사회
  
    + 구성: 총회에서 선출된 54개 이사국으로 구성되며, 임기는 3년으로 18개국 씩 매년 선출되며 재선될 수 있다. 
    + 권한: 경제사회이사회의 임무는 총회와 함께 그 관할 하에 경제적 및 사회적인 국제협력을 행하는 것이다. 이러한 임무를 수행하기 위하여 일정한 조건하에 권고, 조약안 제출 및 국제회의를 소집할 수 있고, 때로는 협정체결 및 전문기관의 활동을 조정할 임무까지도 가지고 있다. 
    + 의결: 이사국은 1개의 투표권을 가지며, 결의는 출석하여 투표하는 이사국 과반수의 찬성으로 행해진다. 

  + 신탁통치이사회
  
    + 구성: 신탁통치국과 안전보장이사회의 상임이사국 중 신탁통치국이 아닌 국가 및 총회에서 선출된 임기 3년의 국가 등 3종의 국가로 구성된다. 이사국 수는 신탁통치국과 비신탁통치국의 이해관계를 고려하여 동수가 되게 하고 있기 때문에 이사국 수는 일정하지 않다. 
    + 기능: 신탁통치란 기본적으로 과도기적 성격을 갖고 있기 때문에 그 기능이 축소되고 있으며, 현재 신탁통치지역은 하나도 없다. 

  + 국제사법재판소: 국제사법재판소는 국제분쟁을 평화적으로 해결하는 주요 국제사법기관이다(자세한 내용은 분쟁의 사법적 해결방법에서 다루기로 한다).

  + 사무국
  
    + 구성: 1인의 사무총장과 국제연합이 필요로 하는 직원으로 구성된다. 사무총장은 안전보장이사회의 권고에 따라 총회가 임명한다. 헌장에는 임기가 정해져 있지 않으나 관례적으로 5년씩 하고 있으며 재선도 가능하다. 그 밖의  직원은 총회가 작성한 규칙에 따라 사무총장에 의하여 능력, 지리적 배분 등을 고려하여 임명된다. 
    + 기능: 사무국은 각종 회의를 준비하고 문서를 관리하며 회의에 필요한 자료를 작성하는 등의 업무를 행한다. 사무총장 및 직원은 오로지 국제연합에 대해서만 책임을 지며, 직원의 신분보장은 국제연합행정재판소에 의하여 행해진다. 사무총장은 국제평화와 안전을 위협한다고 인정되는 사항에 대하여 안전보장이사회에 대하여 주의를 촉구할 수 있다. 

#### 국제기구의 법인격
##### 의의
국제기구가 국제법상 어떠한 권리ㆍ의무를 갖는가를 결정함에 있어서는 당해 국제기구가 국제법인(international person)인가의 여부가 먼저 해결되어야 한다. ICJ에 의하면 국제법인이란 "국제법상의 주체로서 국제적인 권리ㆍ의무를 가질 자격이 있으며, 그 권리를 국제청구에 의하여 주장할 능력을 갖는 것"(ICJ Reports 1949) 이라고 보고 있기 때문이다. 국제법상 국제기구는 통상 국제청구를 제기할 능력과 조약체결능력, 그리고 특권ㆍ면제를 향유할 능력을 가지기  때문에 국제기구는 국제법인격을 갖고 있다고 보아야 된다. 

##### 국제법상의 권리ㆍ의무
국제기구가 국제법상 어떠한 권리ㆍ의무를 갖는가는 설립조약을 중심으로 관련 조약규정에 의하여 결정된다. 그러나 조약상의 제한이 존재하지 않는다면 그 기능을 충분히 수행하기 위하여 설립조약에 규정되지 않은 권능도 향유할 수 있다는 것이 PCIJ의 입장이다. 

##### 국내법상의 권리ㆍ의무
국제연합헌장 제104조는 국제연합 가맹국 내에서의 법률상 능력에 대하여 "이 기구는 그 임무수행 및 목적달성을 위하여 필요한 법률상 능력을 각 가맹국 영역에서 향유한다"고 규정하고 있다. 오늘날 국제기구의 국내법상 법인격에 대하여는 설립조약과 각 국제기구가 본부소재지국과 체결하는 본부협정에 둔 일반적 조문에 의하도록 하고 있다. 

##### 국제기구가 직원과의 관계상 갖는 권리ㆍ의무
국제기구는 소속 직원과 관련하여 직무규칙상의 법률관계를 갖는다. 국제연합 사무직원이 그 고용계약과 채용조건에 관하여 불복할 경우 사무총장을 상대로 국제연합행정재판소에 소송을 제기할 수 있다. 동 소송은 일심제이며 원칙적으로 상소할 수 없다. 그러나 ICJ는 권고적 요청에 의거 상급심의 역할을 할 수 있다. 

#### 국제기구의 조약체결권
특정 국제기구가 조약체결권을 갖는가의 구체적인 판단과 어느 범위까지 갖는가는 설립조약 내지 기타 관련규정을 참조하여 결정되어야 한다. 그러나 오늘날 국제기구의 조약체결권을 둘러싼 문제에 대해서는 1986년 '국가와 국제기구간 및 국제기구 상호간의 조약법에 관한 비엔나 협약'이 채택되어 있다. 

#### 국제기구의 소송당사자능력
##### 국제소송
국제청구권과 구별되는 국제기구의 국제소송능력은 일반적으로 인정되지 않는다. ICJ규정 제34조에서 "국가만이 재판소에 계속하는 사건의 당사자가 될 수 있다"고 규정하고 있기 때문이다. 그러나 제한적으로 국제소송능력을 인정받는 경우도 있다(예: 해양법 재판소에서는 심해저기구의 국제소송능력을 인정하고 있다).

##### 국내소송
국제기구는 가맹국의 국내법원에 제소할 자격을 일반적으로 가지며, 소송을 제기할 능력을 설립조약이나 특권ㆍ면제조약 및 본부협정 중 기구법인격의 속성의 하나로 규정된다. 

#### 국제기구와 그 직원의 특권과 면제
##### 특권과 면제의 성격
국제기구에 있어서 그 임무의 효과적 수행에 필요한 범위 내에서 주권국가의 간섭을 배제하기 위하여 국제기구와 그 직원에게 외교특권에 유사한 일정한 특권과 면제를 부여하고 있다. 그러나 이러한 특권은 외교특권과는 상당한 차이가 있다. 

##### 국제기구 및 그 직원이 향유하는 특권과 면제의 내용
국제기구의 재산은 불가침이며 통신 및 왕래의 자유가 보장되고, 직원의 임무수행을 위해 여권과 유사한 통행증(laissez-passer)을 발급할 수 있다. 기구의 직원 중 상급직원과 가맹국의 대표 및 각 가족은 본부 소재지국에 파견되어 있는 외교사절 및 그 가족에 부여되는 것과 동일한 특권 및 면제를 향유할 수 있다. 다만 기구의 기타 직원은 직무수행에 필요한 범위 내에서 특권과 면제를 향유할 뿐이다.

##### 특권의 남용 및 포기
국제기구 및 직원의 특권에 남용이 있을 경우 개별적으로 그 특권의 포기가 행해져야 한다. 이 경우의 포기는 의무화 되어있다. 국가대표가 향유하는 특권과 면제는 가맹국에 의하여 포기된다. 국제기구와 본부소재지국간에 일어나는 특권ㆍ면제에 관한 분쟁의 해결절차로서는 ICJ를 이용하는 경우와 임시 중재재판소를 이용하는 경우가 있다. 

#### 국제기구와 국제책임
국제기구가 국제법상 책임을 추궁할 자격을 가지며, 국제기구 스스로 국제책임을 지는 지위에 있음은 현실적 실행상 원칙적으로 승인되어 있다고 보인다. 그러나 책임을 지는 경우에 있어서 국제기구는 국가와 그 구조를 달리하기 때문에 국가가 지는 국가책임과 전혀 그 성격을 달리한다는 점이다. 따라서 그 책임의 해제방법도 기존의 국가책임에 있어서의 해제방법과 전혀 달라진다. 

국제연합의 경우 국제연합행정재판소와 각종 청구위원회 그리고 한정적이지만 ICJ에 국제연합이 국제기구로서 부담하는 각종의 권리ㆍ의무관계를 처리하는 주요절차가 마련되어 있다. 

#### 본부소재지국과의 관계
국제기구가 그 본부를 두고 있는 국가를 본부 소재지국이라고 한다. 본부소재지국과 당해 국제기구 사이에 체결되는 협정을 본부협정이라고 한다. 본부지구에 관한 관리권은 국제기구가 보유하며 본부지구는 불가침이지만 본부지구에는 본부 소재지국 및 지방행정단체의 법이 원칙적으로 적용되기 때문에 국제기구는 본부지구에서 비호권을 갖지 못함은 물론 장소 변경 등의 경우 본부소재국의 동의를 요한다. 

## 개인과 법인
### 개인과 법인의 국제법 주체성
모든 법이 자연법에서 유래한다고 생각되던 17C에는 국제법과 국내법을 엄격하게 구별하지 않았다. 따라서 개인이 국제법상 법적 인격을 갖는다는 추론이 가능하였다. 그러나 법실증주의가 지배적인 법철학으로 자리 잡게 된 19C에 들어 국가는 국제법상 유일한 주체로 간주되었다. 오늘날 개인(회사)의 국제법인격을 인정하는 경향이 확산은 되고 있으나 그 건수에 있어서 매우 드물고 제한적이며, 국제법인격이 국가에 의해 부여된다는 점에 있어서 파생적이기도 하다. 

### 국적
#### 국적과 그 결정
국적이란 국제법상 일정 목적을 위하여 어느 국가에 속하는 법적 지위로 정의된다. 따라서 국적이란 어떤 개인과 특정 국가를 연결시켜 주는 고리이며, 국가는 자국의 구성원인 국민과 그 이외의 개인을 국적으로 구별한다.  특히 어느 국가의 속지적 관할권과 미치지 않는 공간에서는 국적을 매개로 하는 속인적 관할권이 국가관할권의 주된 기준이 된다. 국제법상 국적부여는 원칙적으로 국가의 국내관할사항이여, 자국의 국적을 어떤 개인에게 부여할 것인가에 관한 권한은 국가에 위임되어있다. 그러므로 각국은 자국민의 요건을 국내법인 국적법에 따라 결정한다.

#### 국적의 득실
##### 선천적 취득
국적은 보통 출생에 의하여 선천적으로 부여되며, 부모가 자국적이면 자국적을 부여하는 혈통주의국가와 자국에서 태어난 자에게 자국적을 부여하는 출생지주의 국가로 분류된다.

##### 후천적 취득
각국은 일정한 요건과 절차 하에 본인의 의사에 의하여 자국적을 취득하는 것을 인정하는데 이를 귀화라고 하며, 이외에도 여러 가지 경우에 있어서 국적변경의 불가피성이 발생하기도 한다(예: 혼인과 입양, 형벌로서의 박탈, 국적상실, 국가영역 변경의 경우 국적의 국가승계 문제 등이 발생할 수 있다).

#### 국적의 저촉과 그 조정
각국이 국적을 부여하는 기준이 통일되어 있지 않기 때문에 이중국적 내지 무국적문제가 발생하는 수가 있다. 이중국적자에 대해서는 실효적 국적의 원칙이 적용된다. 무국적자의 경우 난민의 대우와 거의 동등한 지위를 무국적자일반에게 보장하며, 1961년 '무국적자 감소에 관한 협약'은 체약국 영역에서 태어난 자에 대하여 국적부여의무 등을 규정하고 있다. 
#### 법인(회사)의 국적
각국은 국내법상의 기준에 따라 내국법인과 외국법인을 구별하고, 외국법인의 인허가제도와 권리향유범위를 정하고 있다. 일반적으로 법인에 대한 국적부여의 기준으로는 설립준거법과 본점소재지 등의 객관적ㆍ외형적 기준과 다수주주의 국적(경영지배권)이라는 주관적ㆍ실질적 기준 등 여러 가지가 존재하고 각국에 의한 기준적용이 다양하기 때문에 국제법상 유효한 국적이 기준에 대해서는 아직까지 다툼이 많으며, 특히 외교적 보호권 행사를 위한 국적특정의 경우 매우 복잡한 문제를 야기한다. 

### 외국인에 대한 처우
#### 외국인의 출입국
일반국제법상 국가는 외국인의 입국을 인정해야할 의무를 지지 않으며, 입국에 관하여 각종 조건을 설정할 수 있는 광범위한 재량권을 가진다. 그러나 외국인의 출국은 자유이며 국가는 특별한 이유가 없는 한 출국을 금지시킬 수 없다. 이에 반해 일반국법상 국가는 정당한 이유가 있는 한 외국인을 강제 추방시킬 수 있는 광범위한 재량을 부여받고 있기 때문에 강제퇴거와 범죄인인도 등을 통해  강제 출국시키는 방식을 쓰고 있다. 

#### 외국인의 법적 지위
외국인은 체류국의 국내법을 준수할 의무를 지며, 원칙적으로 영역국 국민과 동일한 의무가 부과되지만 병역과 의무교육 등은 자국민에게만 부과할 수 있는 성질의 의무로 보아 외국인은 면제된다. 이외에도 참정권과 공직에 임할 권리를 인정하지 않는 국가가 많다. 그러나 영역국은 외국인에게 인정된 권리에 대해서는 행정 및 사법상의 보호를 부여하여야 하며 이를 게을리 하면 국제법상의 국제책임을 지게 된다. 이 경우 영역국은 어느 정도의 보호를 해주어야 국제책임을 면할 수 있을 것인가에 대해서 많은 논란이 있어왔다. 이에 대해서 영역국은 외국인에 대해 자국민과 동일한 행정상ㆍ사법상의 보호를 부여할 의무를 지며 이에 위반할 경우 외국인 본국은 영역국에게 국제책임을 물을 수 있는 것으로 이해되고 있다. 

#### 외국인 재산의 보호
외국인 재산의 침해의 유형으로는 국유화, 위장수용, 계약상의 권리 수용, 이권계약의 파기 등이 있으며, 이에 대한 보상기준으로서는 선진국의 경우 '충분하고 실효적이며, 신속한 보상'을 요구하고 있음에 반해 국유화국은 보상은 국내법절차에 따라 결정될 수 있다고 주장한다. 실제의 분쟁해결에 있어서는 '총액일괄지불보상협정'의 체결로 끝나는 경우가 많다. 외국인 투자의 경우는 1965년 IBRD가 '국가와 타국민 사이의 투자분쟁해결에 관한 협약'을 체결하여 국제투자분쟁해결기관(ICSID)으로 하여금 외국투자가와 자본도 입국 사이에 있어서 분쟁해결을 하도록 하고 있다. 

#### 범죄인인도와 난민의 보호
##### 범죄인인도
타국에서 죄를 범하고 자국 내에 체재하는 자를 타국 청구에 응하여 소추 및 처벌을 위하여 인도하는 것을 범죄인 인도라고 하며, 일반 국제법상 국가에게는 범죄인 인도의무가 없다. 따라서 인도는 범죄인 인도조약에 근거하여 또는 청구국과의 상호주의가 확보되는 것을 조건으로 국내법에 따라 행해며, 국제예양에 의할 경우도 있다. 

##### 난민의 보호
난민이란 인종, 종교, 국적 또는 정치적 사상을 이유로 국적국으로부터 박해를 받거나 박해받을 현저한 우려가 있어 외국에 거류하며 국적국으로의 송환을 희망하지 않고 외국의 비호를 구하는 자를 말한다. 난민협약은 체약국에 난민수용까지 부과하는 것은 아니나 추방하거나 본국으로 송환을 해서는 안 되도록 하고 있다 

### 인권의 국제적 보호
#### 인권보호의 국제화
오늘날 인권의 국제적 보장 문제는 국가 간의 권리ㆍ의무관계에서 파생하는 간접적 효과로서가 아니라 인간으로서의 개인의 인권을 직접 승인하여 체약국에게 그 보호 의무를 부과하고자 하는 것이다. 한 국가에서 자국민의 인권보호문제는 전통 국제법에서는 그 국가의 국내관할사항으로서 국가의 자유재량에 맡겨져 왔지만 오늘날 인권의 국제적 보장 문제는 권리로서의 개인의 인권을 보장할 의무를 국가에게 부과하고 있는 것이다. 특히 국제연합헌장은 개인의 인권 및 기본적 자유를 존중할 것을 반복강조하고 있고, 1948년 총회결의에 의한 세계인권선언은 각국의 국내법과 인권조약의 기초가 되고 있다. 

#### 국제적으로 보호되는 인권
##### 국제인권규약
국제인권규약은 사회권적 기본권과 자유권적 기본권을 원칙적으로 구별하여 A규약('경제적ㆍ사회적 및 문화적 권리에 관한 국제규약')과 B규약('시민적ㆍ정치적 권리에 관한 국제규약')이라는 별개의 조약으로 채택하였다. A규약에는 노동과 사회보장에 관한 권리, 생존권적 권리, 교육권 등이 인정되고, B규약에는 생명ㆍ신체의 자유, 고문ㆍ노예 등의 금지, 이동ㆍ거주의 자유, 공정한 재판을 받을 권리, 사생활의 보호, 사상ㆍ양심ㆍ종교의 자유, 표현ㆍ집회ㆍ결사의 자유 등이 보장되어 있다. 이 두 규약의 차이란 A규약에 비해 B규약은 원칙적으로 즉시 통용 가능한 기준을 정하여 이를 준수ㆍ실시할 의무를 당사국에게 부과하고 있다는 점이다. 

##### 평등원칙의 실현
인권의 평등원칙의 실현을 위해 차별철폐를 구체적으로 규정하고 있는 대표적인 것으로는 '인종차별철폐협약' 과 '여성차별철폐협약'이 있다. 전자가 철폐의 대상으로 한 것은 '인종ㆍ피부색ㆍ문벌 또는 민족적ㆍ종족적 출신에 기인하는 모든 차별' 이며, 후자는 '사회와 가정에서의 남녀 역할분담사상을 부정' 하고, 모든 분야에서 차별철폐를 규정하고 있다. 

##### 자결권과 새로운 인권
A규약과 B규약 제1조 공히 '인민의 자결권'을 규정하였는데, 인민의 정치적 독립뿐만 아니라 경제적인 자립과 발전의 추구를 포함한 내용으로 되어있다. 자결권의 목적은 당초 식민지 인민의 해방(외적 자결)에 있었지만, 오늘날에는 진정으로 인민을 대표하는 정부의 존재(내적 자결)을 문제시하게 되었다. 최근에는 발전의 권리, 평화에 대한 권리, 환경에 대한 권리 등의 새로운 권리개념이 제창되고 있는데, 이를 종합하여 자유권 및 사회권에 이은 '제3세대 인권'이라고 부르기도 한다. 

#### 인권보호의 이행확보조치
##### 국내적 이행확보조치
인권조약에 보장된 권리를 침해당한 개인에게는 일차적으로 국내에서 효과적인 구제를 받을 기회가 부여되어야 하기 때문에, 인권보장 실시조치의 제1단계로 국내절차에 의한 국내적 실시가 있다. 조약상의 권리를 어떠한 수단과 방법을 사용하여 확보하는가는 일반적으로 국가의 재량에 맡겨져 있지만, 인권조약이 국내에서 그대로 적용될 수 있다면 국내적 실시의 확보가 촉진된다고 볼 수 있다(국가재량의 여지가 없는 조약의 경우와 헌법상 동위 내지 우위에 조약이 있는 국가의 경우).

##### 국제적 이행확보조치
인권조약의 대부분은 조약을 실시하기 위한 국제기관을 설치하고 아울러 그 기관에 의한 국제적 실시조치를 정하고 있다. 대표적 실시조치로서는 국가보고제도, 국가통보제도, 개인청원제도가 있고 국제연합에 의한 개인통보제도가 있다. 국제적 인권보호를 위한 국제협약 중에는 국가보고제도만 갖는 조약도 있고(A규약, 여성차별철폐협약 등), 앞의 세 종류 모두 구비한 조약도 있다(B규약 및 B규약 선택의정서, 인종차별철폐협약, 국제노동기구헌장, 아프리카인권헌장 등). 이외에도 유럽인권협약과 미주인권협약은 실시기관인 각 인권위원회에 국가신청 및 개인신청을 인정할 뿐만 아니라 또 하나의 실시기관으로서 인권재판소를 설치하여 체약국과 인권위원회에 재판소에의 제소권을 인정하고 있다. 

  1. 국가보고제도: 인권조약 체약국에 대하여 조약상의 의무의 이행상황을 실시기관에 보고할 의무를 부과하고 이 보고를 실시기관에서 심사하는 절차이다. 

  2. 국가통보제도: 체약국이 타 체약국의 조약의무의 위반사항을 실시기관에 통보하고 이에 근거하여 실시기관이 심사ㆍ조종 및 필요한 권고 등을 행하는 절차이다. 

  3. 개인청원제도: 인권침해의 피해자인 개인과 단체가 피해의 실정을 직접 국제기관에 통보하는 것을 인정하여 이를 처리하는 절차이다.

  4. 국제연합에 의한 개인통보제도
  
  + 인권보호를 위한 국제연합의 절차로서는 국제연합이 인권조약과 별도로 만든 개인통보제도가 있다. 
  + 1970년 경제사회이사회 결의 (1503) '인권 및 기본적 자유의 침해에 관한 통보의 처리절차'에 근거하여 설치된 1503절차로 불리는 것이 그 대표적 예이다. 
    + 1503절차는 개인과 민간단체로부터 들어오는 통보 중 '인권과 기본적 자유에 대한 중대하고 신뢰할 수 있는 증거가 있는 일관된 형태의 침해'로 보이는 통보에 대해서 국제연합 인권위원회 및 그 하부기관인 '차별방지 및 소수자보호위원회'가 비공개로 검토하고 필요할 경우 특정사례의 조사와 경제사회이사회에의 권고를 행하는 것이다. 
    + 1503절차상의 개인통보는 인권침해사태에 대한 정보원으로 취급되는 것이고 개개 인권침해의 피해자를 구제하기 위한 절차는 아니라는 점이다. 

### 개인의 국제범죄
#### 국제범죄의 분류와 섭외성을 갖는 범죄
개인의 국제범죄는 범죄의 구성요건과 소추ㆍ처벌절차를 정한 것이 오로지 국내법인가의 여부에 따라 섭외성을 갖는 범죄와 국제법상의 범죄로 구분할 수 있다. 섭외성을 갖는 범죄는 범죄행위가 국제적인 폭을 지녀 국제협력의 필요도 발생하지만, 이는 국제법에서 정한 범죄가 아니라 원래 국내법상의 범죄이며 따라서 국제법상 협의의 범죄에서는 제외된다. 국제법상의 범죄는 다시 범죄의 추궁에 국내형법의 개입을 필요로 하여 각국 국내법에 근거한 소추ㆍ처벌에 맡겨지던가, 아니면 국제사회전체의 일반법이익을 해하여 그 소추ㆍ처벌이 국제법에 직접 준거하고 원칙적으로 국제기관에 의하여 행해지는 것인가에 따라 각국의 공통이익을 해하는 범죄와 국제사회전체의 이름으로 처벌되는 범죄로 나눌 수 있다. 

#### 국제법이 규정하는 범죄
국제법상의 범죄 중 다수국가가 공통의 이해관계를 갖는 법익을 해하는 행위라서 국제법상의 범죄로 처벌하도록 정해져 있으나 실제 처벌은 각국에 위임되어 있는 범죄를 '각국의 공통이익을 해하는 범죄' 라고 한다. 이러한 국제범죄의 소추ㆍ처벌은 관계 국제법규정의 의거하여 각국이 두는 국내법을 통하여 행해진다(예: 해적, 노예매매, 마약ㆍ향정신성약품의 거래, 해저전선의 손괴 등 각종 해상범죄의 단속 등). 최근에는 국제테러행위에 관한 다국 간 조약은 보편주의를 택할 뿐만 아니라 각 체약국에 대하여 범죄의 소추 및 처벌을 위한 특별의무를 설정하고 있다. 

#### 국제사회전체의 이름으로 처벌하는 범죄
이는 국제사회전체의 일반이익을 해하는 행위이므로 개인의 형사책임이 국내법을 매개로 하지 않고 직접 국제법에 근거하여 성립되며 그 소추 및 처벌이 국제기관에 의하여 직접 행해질 것이 예정된 것으로 제2차 대전 이후 생긴 새로운 형태의 국제범죄이다. 이에 근거하여 처벌한 국제범죄로는 뉘른베르크 국제군사재판소와 극동국제군사재판소에서 재판한 독일 및 일본의 전쟁지도자의 처벌을 들 수 있다. 현재 국제법위원회에서는 '인류의 평화와 안전에 대한 범죄'의 법전화작업이 진행되고 있으며, '집단살해의 방지 및 처벌에 관한 협약' 및 이 조약을 근거로 한 '인종차별범죄의 억제 및 처벌에 관한 국제협약'이 발효 중이다. 이 조약들은 각 범죄를 국제법상의 범죄로 규정하고 범죄구성요건과 개인의 형사책임을 조약 자체가 상세히 정하고 있다. 그리고 국내법원 이외에 국제형사재판소의 설립을 예정하고 있기도 하다. 