# Jurisdiction of States

## 국가관할권
### 국가의 기본적 권리ㆍ의무
국가가 유효한 관할권을 행사하기 위해서는 먼저 권리ㆍ의무의 주체임이 전제되어야 하고, 권리ㆍ의무의 구체적 내용이 무엇인가 하는 것이 확정 되어야 한다. 국가의 권리ㆍ의무로서 열거되는 내용이 확정적인 것은 아니지만 전통적으로 주권, 독립권, 평등권, 자위권, 자기보존권, 교통권, 국내문제불간섭의무 등이 열거되어 왔다. 이러한 내용을 법전화하려는 시도는 성공하지 못했으며 다만 1970년 국제연합총회의 결의 2625로 채택된 '국제연합헌장에 따른 각국 간의 우호관계 및 협력에 관한 국제법원칙에 관한 선언'(일명 우호관계원칙선언)에 의하면 무력행사금지, 분쟁의 평화적 해결의무, 국내문제불간섭의무, 상호협력의무. 인민의 평등권과 자결권, 주권평등, 의무의 성실한 이행 등 7개 항목을 열거하고 있는 데 이는 지금까지 논의된 국가의 권리ㆍ의무내용을 가장 잘 나타내주고 있다고 보인다. 

### 주권
주권이라는 말은 역사적으로 다양하게 사용되어 왔으며, 헤겔의 경우 국제법이란 주권의 자기제한으로 존재함에 그친다고 주장한 바도 있다. 그러나 20세기 들어와서 주권을 근거로 국제법의 타당성을 부정하는 견해는 배척되었고, 주권이란 실정국제법상의 국가권능을 총칭하는 것으로 파악되기 시작했다. 그리하여 오늘날 주권은 대외주권과 대내주권의 두 가지 의미로 파악되며 대외주권이란 독립권을 말하고 대내주권이란 영역권으로서 국가가 영역내의 모든 사람과 물건에 대하여 배타적으로 통치를 행하고 영역을 자유로이 처분할 수 있는 것을 말한다.  

### 국가평등원칙
국가는 동일한 주권을 가지며 평등하게 취급되는 바 이를 국가평등원칙이라고 한다. 일반적으로 평등의 내용으로는 형식적 평등과 실질적 평등의 두 가지를 들고 있으나 전통적으로 국가의 평등으로 생각된 것은 형식적 평등이며 그 내용으로서는 국제법의 정립에 관한 평등과 법 앞의 평등이 열거되어 왔다. 여기서 단순히 형식적 평등만을 적용하게 되면 실질적 불평등이 초래된다는 개발도상국 내지 신생독립국의 의견이 받아들여져 실정 국제법상 그 내용이 반영되기 시작했다는 견해도 있다. 그러나 오히려 실질적 평등은 국제기구의 운영에 있어서 나타나기 시작했으며 이는 선진국의 이익을 대변함은 물론 기능적 평등이라는 이름으로 합리화되고 있다.
  
## 국가관할권의 행사
### 국가관할권의 의의
국가관할권이란 국제법상 한 국가가 자기의 국내법을 통하여 자국의 국민과 재산 등의 일정한 행위와 사실에 대하여 통치할 수 있는 법적 기초를 말한다. 국제법은 국가의 관할권 행사를 무제한 인정하는 것이 아니기 때문에 국내법이 적용되기 위해서는 당해 국가와 행위 및 사실 사이에 일정한 관련이 있어야만 한다. 국내관할권(국내법)이 적용되기 위해서는 다음과 같은 몇 가지 근거를 필요로 한다. 

#### 속지주의 
행위와 사실이 발생한 장소의 소재국임을 근거로 행사되는 관할권을 속지주의라고 하고 이는 국가가 영역주권을 가졌음을 근거로 국제법상 널리 인정되고 있다. 

#### 국적주의 
자국민이 자국영역 밖에서 한 행위에 대하여 관할권을 미치는 경우를 국적주의라고 한다. 이는 속인주의라고도 하며 속지적 관할권과 충돌할 경우 제한을 받는다.   

#### 수동적 속인주의 
외국인이 영역 외에서 한 행위에 의하여 피해를 입은 자가 자국의 속인적 관할권이 미치는 국민과 법인임을 근거로 관할권을 행사하는 것을 수동적 속인주의라고 한다. 

#### 보호주의 
당해 행위에 의하여 국가의 안전과 일체성 등의 중대한 이익이 침해됨을 근거로 실행책임자 및 실행지의 여하를 불문하고 관할권이 행사되는 경우가 있다. 이 경우를 보호주의라고 부른다. 그 판단여하에 따라서 남용의 여지가 없지 않은 제도이다. 

#### 보편주의 
당해 행위를 한자에 대하여 모든 국가에게 관할권을 인정하는 경우를 보편주의라고 한다. 이는 특정국의 기본적 이익에 대한 중대한 침해가 됨을 이유로 하는 것이 아니라, 국제사회에서 보호되어야 할 이익을 침해하는 것을 이유로 관할권 행사가 인정된다는 점에서 보호주의와 구별된다. 해적처벌이나 항공기 납치의 경우 이의 적용에 이의가 없으나 그 외에는 아직까지 그 적용에 있어서 논란의 여지가 많다. 

### 관할권의 충돌시 조정
#### 집행관할권의 조정
집행관할권의 행사는 기본적으로 속지적인 것에 그치며, 타국영역 내에서의 행사는 조약과 기타 동의가 부여될 경우만 예외적으로 인정된다. 

#### 입법관할권의 조정
국내법령을 제정하고 일정한 행위와 사실을 그 적용대상으로 하는 입법관할권에 대한 국제법의 규율은 미비할 뿐만 아니라 국가의 재량에 위임되는 부분이 많기 때문에 경합의 조정을 도모할 필요가 있다. 그러나 입법관할권에 대한 국제법의 제한이 명확하지 않기 때문에 각국은 다만 입법관할권의 존재를 전제로 대항조치 내지 자기억제를 통하여 상호이익을 유지하고 조정할 수밖에 없다. 차후 일반 국제법의 생성이 가장 기대되는 부분이다. 

## 주권면제
### 재판권 면제
#### 의의 
국가는 국가재산 및 국가의 이름으로 한 행위에 대하여 외국 재판관할권의 대상이 되지 않는다. 이러한 원칙을 주권면제라고도 하고 국가면제 내지 국가의 재판권면제라고도 부른다. 면제의 근거로는 전통적으로 국가평등의 원칙 내지 상대국과의 우호관계유지라는 측면이 강조되어 왔다. 그러나 이러한 면제는 포기할 수 있다. 

#### 면제의 주체
주권면제의 원칙 그 자체는 오늘날 국제관습법상 확립되어 있지만, 그것은 주로 각국의 국내법원 판례를 통하여 형성되어 온 것으로서 면제의 주체에 대해서는 통일성이 결여되어 있다. 그러나 주권국가에 대한 면제가 인정된다는 것에 대해서는 이론의 여지가 없으나, 피보호국, 미승인국, 연방국성국, 지방공공단체 등에 대한 면제여부에 대해서는 아직까지 일정한 원칙이 없다. 

#### 면제의 기준
##### 절대면제주의 

면제를 널리 인정하는 전통적인 입장을 절대면제주의라고 한다. 그러나 절대 면제주의에 의한다 하더라도 모든 사항의 면제를 인정하는 것은 아니다. 그것은 절대면제주의가 국가범위에 한정된 것이고, 私人에 의하여 행해지는 경제 활동에는 미치지 않음을 전제로 하고 있었기 때문이다. 그러나 오늘날 국가 활동의 영역이 확대되면서 종래 개인 및 사기업에 위임되어 있던 경제활동에 대한 국가의 개입이 강화되자 국가와 거래하는 개인의 보호라는 측면이 소흘해짐이 지적되었다. 

##### 제한면제주의로의 이행

19세기 말부터 주권적 행위라고 볼 수 없는 국가의 행위에 대하여 재판권면제를 부정하는 판례가 나타나기 시작하자 각국은 국내 판례와 국내입법 내지 조약을 통하여 주권면제 인정범위를 제한하는 주권면제제한경향이 나타나기 시작했다. 따라서 오늘날 국제연합 국제법위원회(ILC:International Law  Commission)에서는 1979년 이래 제한면제주의의 입장에 서서 '국가 및 그 재산에 대한 재판권면제에 관한 협약초안'을 작성하여 1991년에 협약초안으로 최종 채택하였다. 

##### 제한면제주의의 기준

제한면제주의를 채택할 경우 일반적으로 면제가 인정되는 행위와 인정되지 않는 행위의 구별이 필요하다. 통상 면제가 인정되는 행위를 '주권적 행위 또는 권력행위' 라고 부르고, 면제가 인정되지 않는 행위를 '상업적ㆍ관리적 행위 또는 직무행위' 라고 부르며 이 양자를 구별하는 기준에 대한 학설로서는 '행위목적설'과 '행위성질설'이 있다. 그러나 제한면제주의에 관한 상세한 통일적 기준이 결여되어 있기 때문에 과연 제한면제주의가 국제관습법상 확립되어 있다고 말할 수 있느냐가 문제가 된다. 그러므로 면제의 사항적 범위의 결정에는 각국의 재량에 위임될 여지가 많다. 

  1. 행위목적설: 행위목적설이란 당해 활동목적에 착안하여 국가의 주권적 목적 또는 공적 목적을 달성하기 위한 행위였는가에 의하여 판단하는 태로를 말한다. 
  
  2. 행위성질설: 행위성질설이란 당해 행위의 객관적 성질에 착안하여, 계약 등 본래 사인이 행할 수 있는 것에 대하여는 그 목적여하에 관계없이 업무적ㆍ관리적 행위로서 면제를 부정하는 태도를 말한다. 
  
##### 강제집행의 면제여부

재판권면제가 포기되거나 인정되지 않기 때문에 그 결과 재판권이 행사되면 권리보전을 위한 압수와 판결집행을 위한 압류 등의 강제집행이 필요한 경우가 발생하게 된다. 이 경우 새로이 강제집행절차에 대해서도 주권면제가 적용될 수 있는가의 문제가 있다. 스위스와 같이 양자를 연계시켜 재판권 면제를 인정하지 않을 경우 강제집행의 면제도 인정하지 않는 국가도 있으나, 일반적으로 강제집행면제와 재판권면제는 별개로 취급하기 때문에 재판권면제를 인정하지 않더라도 강제집행의 면제는 인정된다고 본다. 설사 강제집행의 여지가 인정되는 경우 집행대상이 되는 재산과 집행면제가 되는 재산은 또한 구분이 된다. 이에 대해서는 집행재산이 주권적 및 공적인 것에 관련되는가, 그렇지 않으면 업무적ㆍ관리적인 것에 관계되는가에 의하여 구별하는 것이 보통이다. 

## 국내문제 불간섭의무
### 의의
국가는 일정사항에 대하여 타국으로부터 간섭을 받지 않고 처리하고 결정할 수 있다. 이러한 사항을 국내문제 내지 국가관할사항이라고 한다. 국내문제란 전통적으로 각국의 정치적 판단에 의하여 주장되었다. 그러나 20세기에 들어와 실정국제법의 규율과 관련하여 국제법의 범주 내에서 국가의 자유재량에 맡겨지는 영역으로 생각되기 시작했다(국제연맹 규약 제15조 8 참조). 따라서 국내문제의 범위는 국제법의 규율이 어디까지 미치는가에 따라 정해지게 된다. 따라서 국내문제는 국제관계의 발전에 수반하는 국제법의 규율이 증대할수록 상대적으로 감소할 수밖에 없다. 그러나 국가의 다양성과 그 주체성을 보호할 뿐만 아니라 타국의 침해로부터 보호되는 영역의 설정이라는 의미에서 여전히 국내문제는 중요하다. 

### 어떠한 간섭이 문제인가?
#### 적법한 간섭
국내문제에 타국이 개입할 경우 국내문제불간섭의무의 위반을 구성하게 된다. 그러나 모든 간섭이 위법한 것은 아니며 다음의 몇 가지는 종래부터 적법한 간섭으로 여겨져 왔다. 먼저 조약에 의한 간섭은 적법하며, 위법행위에 대한 항의와 자위권행사 및 침략에 대한 강제조치 등은 적법하다. 그리고 강제적 요소를 수반하지 않는 단순한 권고와 조언 및 주선이나 중개의 신청 등은 위법한 간섭에 해당하지 않는다. 이외에도 인도를 위한 간섭이 국제법상 허용된다는 주장이 있으나 남용의 위험이 있으므로 국제관습법상 확립된 것으로 보기는 어렵다. 

#### 위법한 간섭
전통적으로 직ㆍ간접적인 무력행사 내지 기타의 강제수단을 사용하여 명령적 개입을 도모할 경우 위법한 간섭을 구성한다. 이에는 군사적 조치를 포함하여, 테러활동 등을 조직하거나 지원하는 일도 해당된다. 이외에도 '우호관계원칙선언'에 의하면 타국의 주권적 권능행사를 종식시키고 일정한 이익을 확보할 목적으로 행해질 경우에는 경제적 및 정치적 강제도 불간섭의무에 위배된다고 보고 있다. 그러므로 오늘날에는 고도의 과학기술을 이용한 활동이 물리적인 손해를 야기하지 않는다고 하더라도 타국의 국내문제에 대한 간섭을 야기할 우려가 있을 때에는 그 활동유형과 방법에 관하여 일정한 제약을 부과하기고 한다. 

#### 내전과 불간섭의무
내전에 관한 불간섭의무는 종래부터 논란이 되어온 부분이다. 전통 국제법에 의하면 합법정부의 원조요쳥에 의한 지원은 간섭이 아니나, 반란단체에 대한 지원은 간섭을 구성한다는 논리였다. 그러나 ICJ의 최근태도는 정부의 요청에 의한 지원이나 반란군 측의 요청에 의한 지원 모두 원조를 정당화하는 것이 아니라고 함으로써(ICJ의 '니카라과에 대한 군사적 활동사건, 1986 참조) 국제법상 내전에 대한 불간섭의무가 원칙적으로 확립된 것으로 보인다. 이에 대해서는 예외가 있는 바 식민지배하의 인민이 자결과 독립의 권리행사를 위해 투쟁하는 것을 정당한 것으로 인정하여 모든 국가에 대하여 물질적ㆍ정신적 지원을 부여하도록 하고 있다(1965년의 국제연합총회 결의 2105 '식민지제국 및 제인민에 대한 독립부여에 관한 선언의 이행' 참조). 물론 이에 대해서도 지원의 내용과 관련하여 해석상의 차이는 있다. 

#### 국제기구에 의한 국내관할사항에 대한 간섭문제
##### 의의

국제기구에 있어서는 국가 간의 문제와는 별도로 국제기구가 가맹국의 국내관할사항에 어디까지 개입하는 것이 허용되는가 하는 문제가 생긴다. 이에 대해서는 국제연맹과 국제연합사이에 약간의 차이가 있다. 

##### 국제연맹의 경우

국제연맹규약은 국제연맹의 분쟁처리권능의 한계로서 국내관할사항에의 불개입 원칙을 규정하였다. 이는 분쟁당사국의 일방이 당해 분쟁에 대하여 '국제법상 오로지 국내관할에 속하는 사항임을 주장하고 연맹이사회도 이에 동의할 경우 그 해결에 대하여 연맹이사회는 어떠한 권고도 할 수 없다'고 하고 있다. 따라서 국제연맹의 경우 국내관할사항에 속하는지의 판단여부는 연맹이사회에 있는 것이다. 

##### 국제연합의 경우

국제연합헌장에서는 국제연합의 활동일반에 대하여 국내문제불간섭의 원칙을 규정함과 아울러 그 적용의 예외로서 헌장 제7장에 의한 강제조치 적용의 경우를 든다. 여기서 불간섭의무는 본질상 가맹국의 국내관할 내에 있는 사항에 대하여 부과되는 데, 국제연합의 관행상 국내관할 사항에 속하는지의 결정은 그 문제를 취급하는 당해 관계기관( 총회 및 안전보장이사회 )에 위임되어 있다. 간섭의 유형에 있어서도 일반국제법상의 간섭이 기본적으로 '명령적 개입'을 의미하므로 헌장상의 간섭도 강제와 위협을 수반하는 경우에 한하여 간섭으로 보자는 설이 있으나 국제연합의 활동은 헌장상의 강제조치를 제외하고는 권고적인 성격에 불과하므로 별의미가 없다.  

## 국가영역
### 국가영역과 영역주권
국가영역은 영토와 이에 부수하는 영수 및 영공으로 구성되는 입체적 공간으로서. 영수는 내수와 영해로 구성되며, 영공은 영토 및 영수의 상공부분으로 구성된다. 국가영역은 특정 국가에게 귀속되는 공간이기 때문에 국가는 특별한 국제법상의 제한이 없는 한 원칙적으로 그 영역내의 모든 사람과 물건을 지배하며, 타국의 주권적 기능행사를 막을 수 있다. 이러한 포괄성과 배타성을 갖는 국가의 권능을 '영역주권'이라고 한다. 영역주권에 근거하여 국가는 비로소 국가영역에 대하여 규제권능과 사용권능을 갖게 된다.

### 영해와 해양관할권의 확장
#### 해양영유론의 역사
##### 근대해양법의 발전

국가가 바다에 대해 국가관할권을 주장하기 시작한 것은 이미 중세 말기로 소급된다. 이탈리아의 도시국가들은 무역로를 확보하기 위하여 인근해역의 폐쇄를 주장하기도 했고, 덴마크와 스웨덴의 경우 어업권을 독점하기 위해 발트해의 영유를 주장하기도 하였다. 심지어 근세초기에는 스페인과 포르투갈이 지리상의 발견에 의한 새로운 통상항로를 독점하기 위해서 1493년 양국 간에 체결된 '토르데실라스 조약'에 의해 대서양ㆍ태평양ㆍ인도양 등의 분할영유를 약속하고 타국민의 항행을 금지시킨 바도 있었다.

이에 대해 그로티우스(H. Grotius)는 1609년 간행된 그의 저서 '자유해론'(Mare Liberum)을 통해 실효성 없는 해양영유를 반대하였고, 영국의 존.셀덴(John Selden)은 1635년 간행된 그의 저서 '폐쇄해론'(Mare Clausum)을 통해 어업면허제를 실시하고 있던 영국의 입장을 옹호하면서 물리적 지배에 의한 해양영유를 지지하였다. 1702년 네덜란드의 빈켈스호크(Cornelius van Bynkershoek)가 간행한 '해양의 지배권에 관하여'에 의하면 해양의 영유성을 강조하면서 외양은 실효적 선점과 계속적 점유에 의하여 취득가능하고 연안해의 영유권은 육지로부터의 지배에 의하여 인정될 수 있다고 하였다. 이러한 과정을 거쳐 공해와 연안해가 구분이 되고 후자를 국가영역으로 편입시킬 수 있는 영해제도의 기본이 확립된 것이다. 근대 이후 해양법에 관한 주된 문제는 영해의 범위와 성질을 어떻게 확정할 것인가였으나 영해의 외측은 공해제도가 적용됨에도 불구하고 그 한계는 통일을 보지 못하였다. 

##### 현대의 발전상황

영해제도에 관한 통일논의는 국제연맹 시에도 계속된 바 있지만 조약의 채택에는 실패하였고, 제2차 대전 이후 각국은 바다에 대한 국가관할권을 경쟁적으로 확대해 나가자 해양질서는 더욱 어지러워졌다. 이에 1958년에 열린 제1차 국제연합해양법회의는 영해, 공해, 대륙붕제도 및 공해어업 및 생물자원보존에 관한 4개의 국제협약을 체결하였다. 그러나 여기서도 영해의 폭에 관해서는 합의에 실패하였다. 이어서 위의 4가지 협약이 채택된 지 15년 후에 열린 제3차 국제연합해양법회의에서 채택된 '국제연합해양법협약'은 해양에 관한 모든 법제도를 포함하는 방대한 조약을 만들었고, 나아가 조약의 실효성을 높이기 위해 해양법재판소에 의한 해양분쟁의 강제적 해결절차까지도 마련하였다. 

#### 내수
##### 내수의 법적 지위

내수란 기선의 내측에 있는 수역으로서 항구ㆍ만ㆍ내해 등을 가리키며, 외국선박의 무해통항권이 인정되지 않고 영토와 동일한 영역주권이 미친다. 항구란 선박의 정박과 화물을 하역하기 위한 시설이다, 내수로서의 만은 연안이 동일국가에 속하는 것으로서 일정조건을 충족하여야 하나(1958년 영해협약 제7조) 역사적 만 등 많은 예외가 있어 만구페쇄선을 획선할 시 많은 문제점들을 야기하기도 한다. 둘 이상의 입구를 갖는 내해에 대해서는 조약상의 규정이 없다. 그러나 그 연안이 모두 동일한 국가의 것일 때에는 각 입구에 만에 적용하는 규칙을 적용할 수 있을 것으로 보인다. 

##### 항구에서 외국선박의 지위

1922년에 체결된 '바다항구의 국제제도에 관한 협약'에 의하면 항구의 출입항 및 사용 등에 관하여 체약국 선박에 대하여 자국선박 또는 제3국의 선박과 동일한 대우를 해줄 것을 의무화하고 있다. 또한 입항 중인 외국의 민간선박은 연안국의 영역주권에 근거한 재판권에 따른다. 

그러나 일반적으로 널리 채택되어 있는 프랑스주의에 의할 것 같으면 선박의 내부문제로서 항구의 평온을 해하지 않은 행위는 기국의 관할권을 인정하도록 하고 있다. 반면 영국은 항내의 일체의 범죄에 대하여 연안국의 재판권이 미친다고 하며 이를 영국주의라고 부르기도 한다. 군함 및 비상업용 정부선박은 정박 중 연안국의 재판권에서 면제된다. 그러나 군함의 승무원이 육상에서 공무 외로 행한 범죄에 대해서는 연안국의 재판권이 인정된다. 

#### 영해
##### 영해의 법적 지위

영해에 대한 국가의 권능은 영토에 대해서와 마찬가지로 영해를 통치하고 지배하는 권능뿐만 아니라 그것을 보유하고 처분하는 권능까지도 포함하는 주권설이 가장 유력하다. 그러나 영해를 영토에서 분리하여 보유하거나 처분할 수는 없고, 연안국은 그 영해 내에서 타국의 선박에 무해통항권을 인정하여야 하기 때문에 영토에 대한 주권처럼 완전히 배타적이지도 않다. 영해를 측정하는 기선은 저조선이며, 복잡한 형상을 갖는 해안의 측정기준으로서는 직선기선제도를 인정하고 있다. 이 경우 직선기선이라 함은 해안의 일반적 방향으로부터 떨어져서는 안 되며, 내측 수역은 내수로서 육지와 밀접한 관련을 가져야 한다. 

##### 무해통항권

외국선박의 영해 내에서의 무해통항은 오랜 역사적 관행에 의하여 승인되어 온 제도로서 무해통항이란 1958년 영해협약에 의하면 '연안국의 평화와 질서 또는 안전을 해하지 않는' 항행을 말한다. 여기서 무해에 관한 판단은 특정기준에 한정되어 있지 않으나 국제연합해양법협약은 제19조 2항에서 무해로 되지 않는 활동을 구체적으로 열거하고 있다. 즉 외국선박의 통항은 영해 내에서 다음 활동 중 어느 것을 행하는 경우, 연안국의 평화, 공서 또는 안전을 침해하는 것으로 간주된다. ① 연안국의 주권, 영토보존 또는 정치적 독립에 반하거나 또는 국제 연합헌장에 구현된 국제법 원칙을 위반하는 기타방법에 의한 무력의 위협 또는 행사, ② 어떠한 종류이든 무기를 사용한 훈련 또는 연습, ③ 연안국의 방위 또는 안전에 유해한 정보수집을 목적으로 한 행위, ④ 연안국의 방위 또는 안전에 영향을 미치는 것을 목적으로 한 선전행위, ⑤ 항공기의 선상 발진, 착륙 또는 탑재, ⑥ 군사장치의 선상발진, 착륙 또는 탑재, ⑦ 연안국의 관세, 재정, 출입국 관리 또는 위생에 관한 법령에 반하는 물품, 통화의 양하, 적하 또는 사람의 승선, 하선, ⑧ 본 협약에 반하는 고의적이고 중대한 오염행위, ⑨ 어로활동, ⑩ 조사 또는 측량활동의 수행, ⑪ 연안국의 통신체계 또는 기타 설비, 시설의 방해를 목적으로 한 행위, ⑫ 통항과 직접 관련이 없는 기타 행위이다. 

군함이 무해통항권을 갖는가에 대하여는 종전부터 부정적으로 보는 시각이 강하였으나 아직까지도 이에 관한 의견에 일치를 본 바는 없다. 따라서 군함에 대해 무해통항을 인정하는 국가(미국, 영국, 일본 등)와 사전통고 내지 허가를 요구하는 국가 등 각국의 실행은 일치하고 않고 있다. 그러나 상당수의 국가는 안전보장의 관점에서 규제권이 있다고 주장하고 있다. 한편, 영해 내에서 잠수함 및 기타 잠수 항행기는 해면 위에 부상하고 그 기를 게양하여 항행하여야 한다(해양법협약 제20조).

##### 영해에 대한 연안국의 권리

영해에 대하여 연안국은 다음과 같은 권리를 행사한다. 첫째 어업 및 영해의 해저와 하층토의 자원을 개발할 배타적 권리가 있고, 둘째 영해의 상공을 배타적으로 사용할 권리를 가지며, 셋째 연안무역에 대한 배타적 권리와 함께 넷째 외국선박이 준수해야 할 항행ㆍ위생ㆍ관세 및 출입국관리에 관한 규칙을 제정할 수 있다. 끝으로 무행통항권을 행사하는 상선에 대한 보전처분 및 이러한 선박 내에 있는 사람에 대한 체포를 위한 일정한 권한을 갖는다(1958년 영해협약 제19조 및 제20조 참조)

#### 군도수역
군도수역이란 다수의 섬으로 구성되는 군도국가의 외측 섬을 연결한 직선기선의 내측수역을 말한다. 여기서 말하는 군도국가란 일련의 섬으로 구성되고 그 섬과 수역이 밀접한 관련을 가지며 지리적ㆍ경제적ㆍ역사적으로 일체성을 갖는 국가를 말하는데 실제로는 인도네시아, 필리핀, 피지, 바하마, 파푸아뉴기니아 등이 그 대상이 되는 군도국가이다. 

군도의 기선은 내측의 수역면적과 육지면적이 1대1에서 9대1 사이로 되며, 기선의 길이는 100해리까지 인정된다. 다만 기선전체의 3%까지는 125해리까지 인정된다. 영해와 배타적 경제수역은 이 기선의 외측에 설정되며, 내측은 군도수역으로서 그 지하와 상공을 포함한 공간에 주권이 미친다. 

#### 접속수역
19세기 이래 각국은 영해 외측의 일정수역에서 한정된 특별관할권을 행사하기 위한 법령을 제정하여 왔으며, 상당수의 국가가 접속수역제도를 지지하였지만 의견의 일치를 본적은 없다. 그러나 1958년 영해협약에서 이 제도가 정식으로 인정이 되었으며, 이에 따르면 연안국은 자국의 영해와 내수에서 행해지는 '통관상, 재정상, 출입국관리상 또는 위생상의 규칙' 위반을 방지하기 위하여 연안에서 12해리 범위 내에서 규제권을 행사할 수 있도록 하고 있다( 동협약 제24조). 국제연합해양법협약은 12해리 영해의 채택과 동시에 이 수역을 24해리로 확대하여 접속수역제도를 유지하고 있다(해양법협약 제33조).

#### 대륙붕
##### 대륙붕의 범위

대륙붕이란 원래 지질학상의 개념으로서 그 범위는  1958년 대륙붕에 관한 협약에 의하면 해안에 인접하고 영해 밖 수심 200M까지의 海床 및 그 아래를 가리키나, 수심이 그 이상이 되더라도 천연자원의 개발이 가능하면 대륙붕에 포함된다고 하고 있다. 이러한 기준은 개발기술이 발달함에 따라 대륙붕의 범위가 확대되는 문제점을 안게 되었다. 따라서 국제연합해양법협약에서는 대륙붕의 범위를 연안으로부터 200해리까지 또는 영토의 자연적 연장에 따라 대륙연변부까지의 해저부분으로 하고, 최대폭은 영해의 기선으로부터 350해리 또는 2500M 등심선으로부터 100해리를 넘지 않도록 하고 있다. 

##### 연안국의 권리

연안국은 대륙붕을 탐사하고 그 천연자원을 개발하기 위한 주권적 권리를 가진다. 여기서 말하는 주권적 권리란 어느 국가도 연안국의 명시적인 동의가 없이는 이들 활동을 하거나 권리를 주장할 수 없다는 의미에서 배타적이다. ICJ는 1969년 '북해대륙붕 사건'을 통해 대륙붕에 대한 연안국의 권리는 "당연히 최초부터" 존재하는 고유한 권리하고 함으로써 연안국의 시원적 권리임을 인정하고 있다. 

#### 배타적 경제수역
##### 의의

배타적 경제수역제도란 영해의 기선으로부터 200해리까지의 수역으로서 그 출발은 영해 밖 연안해역의 천연자원에 대한 연안국의 영구적 주권을 주장하기 위해 중남미국가 및 아프리카국가들에 의해 먼저 제창되었다. 이러한 논의가 계속되자 제3차 국제연합해양법회의는 배타적 경제수역이라는 개념을 인정하여 연안국의 권리ㆍ의무와 타국의 권리ㆍ의무를 조정하여 구체적 제도로서 정립하였다. 이러한 배타적 경제수역이라는 제도의 법적 성격을 어떻게 정할 것인가 하는 것은 확정된 바 없으나 기본적으로 공해의 성격을 가짐과 동시에 특별한 법제도가 적용되는 고유한 수역으로 파악하고 있다.

##### 연안국의 권리

배타적 경제수역제도는 대륙붕제도와 달리, 연안국이 국내입법조치 등에 의해 배타적 경제수역을 설정한 경우에만 그 수역 내의 생물자원 및 비생물자원의 탐사ㆍ개발ㆍ보존 및 관리를 목적으로 한 주권적 권리를 행사할 수 있다. 그러나 배타적 경제수역제도와 저촉되지 않는 한 공해제도에 관한 국제법상의 제규칙은 그대로 적용된다.

#### 해양의 경계획정
국가관할권이 미치는 국가영역을 확정하기 위해서는 경계선이 확정되어 있어야 한다. 그러나 해양관할권에 관한 새로운 제도들은 생긴 지가 얼마 되지 않았기 때문에 국가 간에는 새로운 제도에 의거 국가 간의 해양경계획정을 할 필요가 생겼다. 현재까지 주로 해양 경계획정분쟁이 일어난 분야는 공유대륙붕의 경계획정에 관한 것이다. 1958년 대륙붕협약은 그 경계획정 시 연안국의 합의에 의해 하도록 하고 있고, 합의가 없는 경우에는 특수한 사정에 의해 다른 경계선이 정당하다고 인정되지 않는 한 마주보는 경우에는 '중간선', 이웃하는 경우에는 '등거리선'을 기준으로 하도록 하고 있다(동협약 제6조).

그러나 ICJ는 '북해대륙붕 사건' 판결에서 모든 경우에 의무적인 경계획정의 유일한 방법은 없다고 하며, 경계획정은 '형평의 원칙'에 따라 합의에 의해 행해져야 한다고 한 바 있다. 이 후에도 몇 개의 대륙붕경계획정 판결이 있으나 일관된 입장은 나타나지 않고 있으며 일반적 경향은 분쟁해역의 지질학적 구조나 경제적 요인보다는 해안선의 일반적 방향에서 측정되는 길이 및 섬의 존재 등 지리적 요인이 중시되는 경향이 있다. 

### 영공
#### 영공의 개념
##### 영공의 법적 지위

  영공이란 국가영역(영토와 영해)의 상측 공간으로서 모든 국가가 그 영역상의 상공에서 "완전하고 배타적인 주권"을 보유한다고 본다(1919년의 파리협약 및 1944년의 국제민간항공협약 참조). 그러나 空域에 관한 국제법상의 정의는 존재하지 않기 때문에 영공의 수평적 한계는 결정할 수 있지만, 영공과 우주공간의 경계를 결정하는 기준(영공의 수직적 기준)은 확정할 수 없다. 따라서 영공 밖에 우주공간이 존재하는 이상 현행 국제법상 인정되고 있는 영공주권은 제한적인 주권이라고 보아야 할 것이다. 

##### 영공침범과 대항조치

영공주권의 절대성에 의하여, 영해에서의 무해통항권과 유사한 권리가 항공기에는 부여되지 않는다. 그러므로 하토국의 허가를 받지 않은 비행 및 착륙은 영공침범으로 국제불법행위를 구성하게 된다. 영공침범에 대하여는 필요한 대항조치를 취할 수 있으며 이러한 대항 조치를 위법으로 하는 국제조약 내지 국제관습법은 아직 존재하지 않는다. 여기서 영공을 침범한 민간여객기에 대해서 영역국이 무력을 행사할 수 있는가라는 문제가 생긴다. 이 문제에 대해서는 아직까지 명확한 규정이 없다. 

다만 1983년 '대한항공기격추 사건'을 계기로 국제민간항공기구는 1984년 5월 특별총회를 통해 모든 국가는 비행중인 민간항공기에 대한 무기사용을 삼가야 하고, 침입기를 요격할 경우에는 항공기내 사람의 생명과 항공기의 안전을 위태롭게 해서는 안 된다는 것을 내용으로 하는 새로운 규정을 전원일치로 채택한 바 있을 뿐이다. 

#### 항공의 국제제도
##### 의의

영공에 관한 완전하고 배타적인 영역국의 주권행사는 조약에 의하여 제한된다. 시카고협약은 영공에 있어 민간항공기의 비행의 자유를 인정하였는데 이는 영공주권을 전제로 조약에 의하여 특별히 타국의 민간 항공기에 대해 무해통항권을 인정하려는 것이다.  

##### 부정기비행의 권리

시카고협약 체약국의 민간 항공기는 부정기항공에 의해 다른 체약국의 영공을 비행할 수 있는 권리를 갖는다. 그러나 이에는 영역국의 착륙요구와 항공로지점 및 특별허가에 따를 것이 조건이다. 

##### 정기국제항공업무

시카고협약은 정기국제항공업무와 관련하여 체약국에게 사전 특별허가를 요구하면서 동협약의 채택시 다른 두 개의 부속협정 즉 '국제항공업무통과 협정'과 '국제항공운송협정'을 채택한 바 있다. 전자의 협정에는 많은 국가가 가입하고 있지만, 후자의 경우에는 가입한 국가가 별로 없기 때문에 일반적으로 비체약국과의 관계에서는 '2국간 항공협정'에 의하여 국제정기항공로가 개설되고 있다.

### 영역의 취득
#### 의의
국제법상 영역권원이란 국가가 특정지역에 대하여 영역주권을 유효하게 행사할 수 있는 원인 내지 근거가 되는 사실을 말한다. 이 권원에 의하여 특정지역이 국가에 귀속되고 거기에 국가의 속지적 권능이 행사되는 것이다. 국가가 영역권원을 취득하는 주요 유형으로는 선점, 할양, 병합, 정복, 시효, 첨부 등이 있으며 이는 다시 원시취득과 승계취득, 쌍방행위에 의한 취득과 일방적 행위에 의한 취득, 국가에 의한 취득과 자연적 취득 등으로 다시 나누어서 볼 수 있다. 

#### 국가에 의한 취득
##### 선점

선점이란 무주지역, 즉 취득 직전 어느 국가에도 속하지 않았던 지역을 취득하는 것을 말한다. 국제법상 선점의 요건으로서는 로마법상의 무주물선점의 법리를 유추하여 다음의 네 가지를 들고 있다. 첫째, 선점의 주체는 국가이어야만 한다. 둘째, 선점의 대상이 되는 지역은 무주지여야만 한다. 셋째, 국가는 무주지를 영유할 의사를 보여야 한다. 넷째, 선점은 실효적 점유를 수반하여야 한다. 

##### 할양

  할양이란 국가 간의 합의(조약)에 의하여 국가영역의 일부를 타국에 이전하는 것으로서, 양도국이 당해 영역에 대하여 갖는 권리와 권원을 타국을 위하여 포기하는 것을 말한다. 역사적으로 볼 때 할양하는 방식에는 유상의 매매방식과 무상에 의한 할양 및 영토교환을 위한 할양이 있었으나, 오늘날 평화조약에 의한 할양을 별도로 하면 할양에 의한 영역변동은 거의 없다고 볼 수 있다. 

##### 병합

  병합이란 조약에 의하여 국가영역의 전부를 양수하는 것을 말한다. 병합에 의하여 피병합국은 소멸하며, 그 국민은 종전의 국적을 상실하고 병합국의 국적을 얻는다. 그러나 오늘날 강제로 맺은 조약은 무효이다.

##### 정복

  정복이란 국가가 실력에 의하여 타국영역을 취득하는 것으로서, 강제적 병합이라고도 불린다. 정복된 국가가 소멸된다는 점에서 병합과 정복은 동일한 효과가 있다. 정복이 유효하게 성립하기 위해서는 타국영역에 대한 실효적 지배의 확립과 정복국의 영유의 의사가 필요하다. 현행 국제법상 무력행사는 일반적으로 금지되기 때문에 영역권원으로서의 정복은 인정되지 않는다.

#### 자연적 취득
##### 시효

  시효란 영역을 실효적으로 지배하는데 기초가 되기 때문에 국가가 타국의 영역을 상당기간 계속하여 평온하게 또는 주권자로서 영유할 의사를 가지고 지배한 경우에 이를 취득하게 되는 것을 시효에 의한 취득이라고 한다. 그러나 이러한 시효에 의한 국가영역의 취득을 국제법상 인정할 것인가에 대하여는 논란의 여지가 많다. 시효중단의 방법으로서는 외교항의로 충분하다는 견해와  국제재판에 사건부탁을 할 때 비로소 시효가 중단이 된다는 견해로 나뉘고 있다.

##### 첨부

  첨부란 통상적으로 볼 때 하구와 해안에 있어서 토사퇴적과 해저의 융기 등 자연현상에 의하여 국가영역의 범위가 확대되는 것을 말한다. 이 경우 영역확대는 점진적인 과정을 거치므로, 새로 발생한 영역의 귀속에 대해서 국가에 의한 특별한 행위와 절차는 불필요하며, 귀속처인 국가의 실효적 점유에 유리한 추정이 작용한다. 인공적인 첨부도 인정된다. 

##### 인접성의 원칙

  무주지가 국가영역과 지리적으로 근접하고 있거나 혹은 그 국가영역의 자연적 연장부분을 이룬다는 사실이 영역권원으로 주장될 경우가 있는데 이를 인접성의 원칙이라고 한다. 그러나 이러한 지리적 또는 자연적 사실이 일반국제법상 영역권원으로 인정되지는 않는다. 영토에 접속된 특정해역 등에 있어서 국가관할권의 행사가 인정되는 것은 특정한 목적과 기능을 갖는 한정적 기능을 연안국에게 부여하는 특별한 제도에 의해서이지 인접성의 원칙이 적용된 결과는 아닌 것이다. 국제 판례도 인접성의 사실을 유효한 영역권원으로 인정하고 있지 않다('팔마스섬 사건').

#### 영역취득에 관한 기타 이론
##### 판결

  판결이 때로는 영역취득의 한 방식이 된다는 이론이 있다. 그러나 이론적으로 볼 때 재판소의 통상임무는 당사자가 이미 갖고 있는 권리를 선언하는 것이고, 새로운 권리를 창설하여 주는 것은 아니다. 따라서 판결로 인해 국가가 그 당시까지 소유하지 않았던 지역을 그 국가에 부여할 수는 없다. 

##### 묵인ㆍ승인 및 금반언

  묵인ㆍ승인 및 금반언은 엄밀하게 말해서 영역취득의 방식은 아니지만, 영역취득시 중요한 역할을 한다. 특히 승인과 묵인은 시효에 있어서 결정적 역할을 한다 ('동부그린란드 사건'). 승인 또는 묵인은 금반언을 발생한다고 말하여진다. 즉 영역에 대한 국제분쟁에 있어서, 특정영역에 대한 다른 국가의 권원을 승인한 국가는 타국이 그 승인에 의거하여 어떤 행위를 할 때, 타국의 권원을 부인하는 것이 금반언에 의하여 금지된다는 것이다. 그러나 금반언에 대한 국제법의 태도는 일정하지 않다. 

##### 시제법

  영역에 대한 권원의 유효성을 결정하기 위하여 어느 시대의 법이 적용되어야 하는가의 문제가 있다. 이것이 시제법의 문제이다. 일반적으로 인정된 견해는 영역취득의 유효성은 그 취득이 주장되는 시점에서 효력을 갖는 법에 기초한다는 것으로서, 법률은 소급 적용되지 않는다는 법일반원칙을 말하고 있는 것이다. 그러나 권리창설과 권리존속은 구별되어야 하며, 권리의 계속은 법의 발전에 따라 요구되어지는 조건을 따라야 한다는 이론이 나왔다('팔마스섬 사건에 대한 막스후버 판사의 견해). 
  
이러한 견해는 정복에 근거한 권원일 경우 매우 심각한 사태를 발생시키기 때문에(인도의 고아사태) 1970년 국제연합총회는 정복에 의한 영역취득의 금지는 "헌장제도 이전에 또는 전통 국제법하에서 유효하게" 창설된 영역에 대한 권원에 영향을 주는 것으로 해석되어서는 안 된다고 선언까지 한 바 있다. 

##### 영역에 대한 부차적 권리

  1. 공동영유권의 설정: 2개국이 특정영역에 대해서 공동으로 주권을 행사하기로 합의하는 경우가 있다. 이는 국내법상의 공동소유권과 비슷하며, 태평양상에 있는 뉴헤브리지스섬에 대하여 프랑스와 영국이 공동영유권을 행사하고 있다. 

  2. 租借地의 설정: 국가가 타국과의 특별한 합의에 의하여 타국 영역의 일부를 차용하는 것을 조차(lease)라고 하는데, 이때 차용하는 국가를 조차국, 조차의 대상이 되는 지역을 조차지라고 한다. 조차국은 조차협정이 효력을 갖는 한 그 영역에 대하여 완전한 주권을 행사할 수 있기 때문에 이것을 사실상 영역의 잠정적 양도가 되는 것이다. 

  3. 國際地役의 설정: 국제지역이 설정된 경우란 어느 국가에 속하는 영역이 특정방법에 의하여 타국에 이익이 되도록 이용되게 하는 때를 말한다. 따라서 地役에 의해 이익을 향유하는 국가는 당해 영역을 사용할 수 있는 권리, 예컨대 통행권, 혹은 관개용수를 취입할 권리를 가진다. 이에 대하여 地役의 부담을 지는 국가는 일정행위를 삼가할 의무, 예컨대 당해 영역에 요새를 설치하거나 군대를 두지 않을 의무를 진다. 지역을 일반적으로 조약에 의해 설정되지만 지방적 관습에 의해서도 성립할 수 있다. 